const sfy_vanilla = {}
export default sfy_vanilla

sfy_vanilla.id = 'sfy_vanilla'
sfy_vanilla.title = 'sfy_vanilla_title'
sfy_vanilla.subtitle = 'sfy_vanilla_subtitle'
sfy_vanilla.desc = 'sfy_vanilla_desc'

sfy_vanilla.victoryReqs = { 'phase_5':1 }

sfy_vanilla.elems = [

	// MILESTONES
	
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_1',	name:'sfy_hub_upgrade_1',	},	
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_2',	name:'sfy_hub_upgrade_2',	reqs:{ 'hub_upgrade_1':1 },	},
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_3',	name:'sfy_hub_upgrade_3',	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_5',	name:'sfy_hub_upgrade_5',	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_6',	name:'sfy_hub_upgrade_6',	reqs:{ 'hub_upgrade_5':1 },	},
							
	{	type:'milestone',	group:'sfy_order',	id:'part_asssembly',	name:'sfy_part_asssembly',	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'coal_power',	name:'sfy_coal_power',	reqs:{ 'phase_1':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'basic_steel_production',	name:'sfy_basic_steel_production',	reqs:{ 'phase_1':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'logistics',	name:'sfy_logistics',	reqs:{ 'basic_steel_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'advanced_steel_production',	name:'sfy_advanced_steel_production',	reqs:{ 'basic_steel_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'oil_processing',	name:'sfy_oil_processing',	reqs:{ 'phase_2':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'petroleum_power',	name:'sfy_petroleum_power',	reqs:{ 'oil_processing':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'industrial_manufacturing',	name:'sfy_industrial_manufacturing',	reqs:{ 'oil_processing':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'bauxite_refinement',	name:'sfy_bauxite_refinement',	reqs:{ 'phase_3':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'control_system_development',	name:'sfy_control_system_development',	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'nuclear_power',	name:'sfy_nuclear_power',	reqs:{ 'control_system_development':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'advanced_aluminum_production',	name:'sfy_advanced_aluminum_production',	reqs:{ 'control_system_development':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'leading_edge_production',	name:'sfy_leading_edge_production',	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'particle_enrichment',	name:'sfy_particle_enrichment',	reqs:{ 'leading_edge_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'matter_conversion',	name:'sfy_matter_conversion',	reqs:{ 'phase_4':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'quantum_encoding',	name:'sfy_quantum_encoding',	reqs:{ 'matter_conversion':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'spatial_energy_regulation',	name:'sfy_spatial_energy_regulation',	reqs:{ 'quantum_encoding':1 },	},
							
	{	type:'milestone',	group:'sfy_project',	id:'phase_0',	name:'sfy_phase_0',	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_1',	name:'sfy_phase_1',	reqs:{ 'part_asssembly':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_2',	name:'sfy_phase_2',	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_3',	name:'sfy_phase_3',	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_4',	name:'sfy_phase_4',	reqs:{ 'particle_enrichment':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_5',	name:'sfy_phase_5',	reqs:{ 'spatial_energy_regulation':1 },	},
	
	// ENERGY
	
	{	type:'power',	id:'energy',	name:'sfy_energy',	img:'/fgfactory/sfy/energy.png',	reqs:{ 'hub_upgrade_2':1 },	},
	
	// GENERATORS
	
	{	type:'generator',	id:'biomass_burner',	name:'sfy_biomass_burner',	img:'/fgfactory/sfy/biomass_burner.png',	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'generator',	id:'coal_generator',	name:'sfy_coal_generator',	img:'/fgfactory/sfy/coal_generator.png',	reqs:{ 'coal_power':1 },	},
	{	type:'generator',	id:'fuel_generator',	name:'sfy_fuel_generator',	img:'/fgfactory/sfy/fuel_generator.png',	reqs:{ 'petroleum_power':1 },	},
	{	type:'generator',	id:'nuclear_power_plant',	name:'sfy_nuclear_power_plant',	img:'/fgfactory/sfy/nuclear_power_plant.png',	reqs:{ 'nuclear_power':1 },	},
	
	// BUILDINGS
	
	{	type:'building',	group:'sfy_container',	id:'storage_container_1',	name:'sfy_storage_container_1',	img:'/fgfactory/sfy/storage_container_1.png',	reqs:{ 'hub_upgrade_5':1 },	},
	{	type:'building',	group:'sfy_container',	id:'storage_container_2',	name:'sfy_storage_container_2',	img:'/fgfactory/sfy/storage_container_2.png',	reqs:{ 'logistics':1 },	},
	{	type:'building',	group:'sfy_container',	id:'fluid_buffer_1',	name:'sfy_fluid_buffer_1',	img:'/fgfactory/sfy/fluid_buffer_1.png',	reqs:{ 'coal_power':1 },	},
	{	type:'building',	group:'sfy_container',	id:'fluid_buffer_2',	name:'sfy_fluid_buffer_2',	img:'/fgfactory/sfy/fluid_buffer_2.png',	reqs:{ 'petroleum_power':1 },	},
								
	{	type:'building',	group:'sfy_extractor',	id:'miner_0',	name:'sfy_miner_0',	img:'/fgfactory/sfy/miner_0.png',	reqs:{ 'hub_upgrade_1':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'miner_1',	name:'sfy_miner_1',	img:'/fgfactory/sfy/miner_1.png',	reqs:{ 'hub_upgrade_5':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'miner_2',	name:'sfy_miner_2',	img:'/fgfactory/sfy/miner_2.png',	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'miner_3',	name:'sfy_miner_3',	img:'/fgfactory/sfy/miner_3.png',	reqs:{ 'leading_edge_production':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'water_extractor',	name:'sfy_water_extractor',	img:'/fgfactory/sfy/water_extractor.png',	reqs:{ 'coal_power':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'oil_extractor',	name:'sfy_oil_extractor',	img:'/fgfactory/sfy/oil_extractor.png',	reqs:{ 'oil_processing':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'gas_extractor',	name:'sfy_gas_extractor',	img:'/fgfactory/sfy/gas_extractor.png',	reqs:{ 'advanced_aluminum_production':1 },	},
	
	{	type:'building',	group:'sfy_machine',	id:'smelter',	name:'sfy_smelter',	img:'/fgfactory/sfy/smelter.png',	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'builder',	name:'sfy_builder',	img:'/fgfactory/sfy/builder.png',	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'assembler',	name:'sfy_assembler',	img:'/fgfactory/sfy/assembler.png',	reqs:{ 'part_asssembly':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'foundry',	name:'sfy_foundry',	img:'/fgfactory/sfy/foundry.png',	reqs:{ 'basic_steel_production':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'refinery',	name:'sfy_refinery',	img:'/fgfactory/sfy/refinery.png',	reqs:{ 'oil_processing':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'manufacturer',	name:'sfy_manufacturer',	img:'/fgfactory/sfy/manufacturer.png',	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'blender',	name:'sfy_blender',	img:'/fgfactory/sfy/blender.png',	reqs:{ 'control_system_development':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'particle_accelerator',	name:'sfy_particle_accelerator',	img:'/fgfactory/sfy/particle_accelerator.png',	reqs:{ 'particle_enrichment':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'converter',	name:'sfy_converter',	img:'/fgfactory/sfy/converter.png',	reqs:{ 'matter_conversion':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'quantum_encoder',	name:'sfy_quantum_encoder',	img:'/fgfactory/sfy/quantum_encoder.png',	reqs:{ 'quantum_encoding':1 },	},
	
	// ITEMS
	
	{	type:'item',	group:'sfy_raw',	id:'iron_ore',	name:'sfy_iron_ore',	img:'/fgfactory/sfy/iron_ore.png',	max:100,	},	
	{	type:'item',	group:'sfy_raw',	id:'copper_ore',	name:'sfy_copper_ore',	img:'/fgfactory/sfy/copper_ore.png',	max:100,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'limestone',	name:'sfy_limestone',	img:'/fgfactory/sfy/limestone.png',	max:100,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'biomass',	name:'sfy_biomass',	img:'/fgfactory/sfy/biomass.png',	max:200,	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'coal',	name:'sfy_coal',	img:'/fgfactory/sfy/coal.png',	max:100,	reqs:{ 'coal_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'water',	name:'sfy_water',	img:'/fgfactory/sfy/water.png',	max:400,	reqs:{ 'coal_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'crude_oil',	name:'sfy_crude_oil',	img:'/fgfactory/sfy/crude_oil.png',	max:400,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'caterium_ore',	name:'sfy_caterium_ore',	img:'/fgfactory/sfy/caterium_ore.png',	max:100,	reqs:{ 'petroleum_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'bauxite',	name:'sfy_bauxite',	img:'/fgfactory/sfy/bauxite.png',	max:100,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'raw_quartz',	name:'sfy_raw_quartz',	img:'/fgfactory/sfy/raw_quartz.png',	max:100,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'sulfur',	name:'sfy_sulfur',	img:'/fgfactory/sfy/sulfur.png',	max:100,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'uranium',	name:'sfy_uranium',	img:'/fgfactory/sfy/uranium.png',	max:100,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'nitrogen_gas',	name:'sfy_nitrogen_gas',	img:'/fgfactory/sfy/nitrogen_gas.png',	max:400,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'sam',	name:'sfy_sam',	img:'/fgfactory/sfy/sam.png',	max:100,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'excited_photonic_matter',	name:'sfy_excited_photonic_matter',	img:'/fgfactory/sfy/excited_photonic_matter.png',	max:400,	reqs:{ 'quantum_encoding':1 },	},
	
	{	type:'item',	group:'sfy_material',	id:'iron_ingot',	name:'sfy_iron_ingot',	img:'/fgfactory/sfy/iron_ingot.png',	max:100,	},	
	{	type:'item',	group:'sfy_material',	id:'copper_ingot',	name:'sfy_copper_ingot',	img:'/fgfactory/sfy/copper_ingot.png',	max:100,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_material',	id:'concrete',	name:'sfy_concrete',	img:'/fgfactory/sfy/concrete.png',	max:500,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_material',	id:'steel_ingot',	name:'sfy_steel_ingot',	img:'/fgfactory/sfy/steel_ingot.png',	max:100,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_material',	id:'plastic',	name:'sfy_plastic',	img:'/fgfactory/sfy/plastic.png',	max:200,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_material',	id:'rubber',	name:'sfy_rubber',	img:'/fgfactory/sfy/rubber.png',	max:200,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_material',	id:'fuel',	name:'sfy_fuel',	img:'/fgfactory/sfy/fuel.png',	max:400,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_material',	id:'caterium_ingot',	name:'sfy_caterium_ingot',	img:'/fgfactory/sfy/caterium_ingot.png',	max:100,	reqs:{ 'petroleum_power':1 },	},
	{	type:'item',	group:'sfy_material',	id:'aluminum_ingot',	name:'sfy_aluminum_ingot',	img:'/fgfactory/sfy/aluminum_ingot.png',	max:100,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_material',	id:'quartz_crystal',	name:'sfy_quartz_crystal',	img:'/fgfactory/sfy/quartz_crystal.png',	max:200,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_material',	id:'silica',	name:'sfy_silica',	img:'/fgfactory/sfy/silica.png',	max:200,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_material',	id:'sulfuric_acid',	name:'sfy_sulfuric_acid',	img:'/fgfactory/sfy/sulfuric_acid.png',	max:400,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_material',	id:'ficsite_ingot',	name:'sfy_ficsite_ingot',	img:'/fgfactory/sfy/ficsite_ingot.png',	max:100,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_material',	id:'diamonds',	name:'sfy_diamonds',	img:'/fgfactory/sfy/diamonds.png',	max:200,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_material',	id:'reanimated_sam',	name:'sfy_reanimated_sam',	img:'/fgfactory/sfy/reanimated_sam.png',	max:100,	reqs:{ 'matter_conversion':1 },	},
	
	{	type:'item',	group:'sfy_component_1',	id:'iron_rod',	name:'sfy_iron_rod',	img:'/fgfactory/sfy/iron_rod.png',	max:200,	},	
	{	type:'item',	group:'sfy_component_1',	id:'iron_plate',	name:'sfy_iron_plate',	img:'/fgfactory/sfy/iron_plate.png',	max:200,	reqs:{ 'hub_upgrade_1':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'wire',	name:'sfy_wire',	img:'/fgfactory/sfy/wire.png',	max:500,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'copper_sheet',	name:'sfy_copper_sheet',	img:'/fgfactory/sfy/copper_sheet.png',	max:200,	reqs:{ 'part_asssembly':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'steel_beam',	name:'sfy_steel_beam',	img:'/fgfactory/sfy/steel_beam.png',	max:200,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'steel_pipe',	name:'sfy_steel_pipe',	img:'/fgfactory/sfy/steel_pipe.png',	max:200,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'circuit_board',	name:'sfy_circuit_board',	img:'/fgfactory/sfy/circuit_board.png',	max:200,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'quickwire',	name:'sfy_quickwire',	img:'/fgfactory/sfy/quickwire.png',	max:500,	reqs:{ 'petroleum_power':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'encased_uranium_cell',	name:'sfy_encased_uranium_cell',	img:'/fgfactory/sfy/encased_uranium_cell.png',	max:200,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'copper_powder',	name:'sfy_copper_powder',	img:'/fgfactory/sfy/copper_powder.png',	max:500,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'time_crystal',	name:'sfy_time_crystal',	img:'/fgfactory/sfy/time_crystal.png',	max:200,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component_1',	id:'dark_matter_residue',	name:'sfy_dark_matter_residue',	img:'/fgfactory/sfy/dark_matter_residue.png',	max:400,	reqs:{ 'quantum_encoding':1 },	},
	
	{	type:'item',	group:'sfy_component_2',	id:'cable',	name:'sfy_cable',	img:'/fgfactory/sfy/cable.png',	max:200,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'screw',	name:'sfy_screw',	img:'/fgfactory/sfy/screw.png',	max:500,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'encased_industrial_beam',	name:'sfy_encased_industrial_beam',	img:'/fgfactory/sfy/encased_industrial_beam.png',	max:100,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'stator',	name:'sfy_stator',	img:'/fgfactory/sfy/stator.png',	max:100,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'alumina_solution',	name:'sfy_alumina_solution',	img:'/fgfactory/sfy/alumina_solution.png',	max:400,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'ai_limiter',	name:'sfy_ai_limiter',	img:'/fgfactory/sfy/ai_limiter.png',	max:100,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'uranium_fuel_rod',	name:'sfy_uranium_fuel_rod',	img:'/fgfactory/sfy/uranium_fuel_rod.png',	max:50,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'sam_fluctuator',	name:'sfy_sam_fluctuator',	img:'/fgfactory/sfy/sam_fluctuator.png',	max:100,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component_2',	id:'dark_matter_crystal',	name:'sfy_dark_matter_crystal',	img:'/fgfactory/sfy/dark_matter_crystal.png',	max:200,	reqs:{ 'quantum_encoding':1 },	},
	
	{	type:'item',	group:'sfy_component_3',	id:'reinforced_iron_plate',	name:'sfy_reinforced_iron_plate',	img:'/fgfactory/sfy/reinforced_iron_plate.png',	max:100,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_component_3',	id:'rotor',	name:'sfy_rotor',	img:'/fgfactory/sfy/rotor.png',	max:100,	reqs:{ 'part_asssembly':1 },	},
	{	type:'item',	group:'sfy_component_3',	id:'computer',	name:'sfy_computer',	img:'/fgfactory/sfy/computer.png',	max:50,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'item',	group:'sfy_component_3',	id:'aluminum_scrap',	name:'sfy_aluminum_scrap',	img:'/fgfactory/sfy/aluminum_scrap.png',	max:500,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component_3',	id:'high_speed_connector',	name:'sfy_high_speed_connector',	img:'/fgfactory/sfy/high_speed_connector.png',	max:100,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component_3',	id:'electromagnetic_control_rod',	name:'sfy_electromagnetic_control_rod',	img:'/fgfactory/sfy/electromagnetic_control_rod.png',	max:100,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_component_3',	id:'automated_wiring',	name:'sfy_automated_wiring',	img:'/fgfactory/sfy/automated_wiring.png',	max:50,	reqs:{ 'advanced_steel_production':1 },	},
	
	{	type:'item',	group:'sfy_component_4',	id:'modular_frame',	name:'sfy_modular_frame',	img:'/fgfactory/sfy/modular_frame.png',	max:50,	reqs:{ 'part_asssembly':1 },	},
	{	type:'item',	group:'sfy_component_4',	id:'motor',	name:'sfy_motor',	img:'/fgfactory/sfy/motor.png',	max:50,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'item',	group:'sfy_component_4',	id:'crystal_oscillator',	name:'sfy_crystal_oscillator',	img:'/fgfactory/sfy/crystal_oscillator.png',	max:100,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component_4',	id:'supercomputer',	name:'sfy_supercomputer',	img:'/fgfactory/sfy/supercomputer.png',	max:50,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component_4',	id:'smart_plating',	name:'sfy_smart_plating',	img:'/fgfactory/sfy/smart_plating.png',	max:50,	reqs:{ 'part_asssembly':1 },	},
	
	{	type:'item',	group:'sfy_component_5',	id:'heavy_modular_frame',	name:'sfy_heavy_modular_frame',	img:'/fgfactory/sfy/heavy_modular_frame.png',	max:50,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'item',	group:'sfy_component_5',	id:'alclad_aluminum_sheet',	name:'sfy_alclad_aluminum_sheet',	img:'/fgfactory/sfy/alclad_aluminum_sheet.png',	max:200,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component_5',	id:'aluminum_casing',	name:'sfy_aluminum_casing',	img:'/fgfactory/sfy/aluminum_casing.png',	max:200,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component_5',	id:'versatile_framework',	name:'sfy_versatile_framework',	img:'/fgfactory/sfy/versatile_framework.png',	max:50,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_component_5',	id:'modular_engine',	name:'sfy_modular_engine',	img:'/fgfactory/sfy/modular_engine.png',	max:50,	reqs:{ 'industrial_manufacturing':1 },	},

	{	type:'item',	group:'sfy_component_6',	id:'radio_control_unit',	name:'sfy_radio_control_unit',	img:'/fgfactory/sfy/radio_control_unit.png',	max:50,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component_6',	id:'battery',	name:'sfy_battery',	img:'/fgfactory/sfy/battery.png',	max:200,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component_6',	id:'heat_sink',	name:'sfy_heat_sink',	img:'/fgfactory/sfy/heat_sink.png',	max:100,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_component_6',	id:'ficsite_trigon',	name:'sfy_ficsite_trigon',	img:'/fgfactory/sfy/ficsite_trigon.png',	max:200,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component_6',	id:'superposition_oscillator',	name:'sfy_superposition_oscillator',	img:'/fgfactory/sfy/superposition_oscillator.png',	max:100,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_component_6',	id:'adaptive_control_unit',	name:'sfy_adaptive_control_unit',	img:'/fgfactory/sfy/adaptive_control_unit.png',	max:50,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'item',	group:'sfy_component_6',	id:'magnetic_field_generator',	name:'sfy_magnetic_field_generator',	img:'/fgfactory/sfy/magnetic_field_generator.png',	max:50,	reqs:{ 'nuclear_power':1 },	},

	{	type:'item',	group:'sfy_component_7',	id:'cooling_system',	name:'sfy_cooling_system',	img:'/fgfactory/sfy/cooling_system.png',	max:100,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_component_7',	id:'fused_modular_frame',	name:'sfy_fused_modular_frame',	img:'/fgfactory/sfy/fused_modular_frame.png',	max:50,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_component_7',	id:'neural_quantum_processor',	name:'sfy_neural_quantum_processor',	img:'/fgfactory/sfy/neural_quantum_processor.png',	max:100,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_component_7',	id:'assembly_director_system',	name:'sfy_assembly_director_system',	img:'/fgfactory/sfy/assembly_director_system.png',	max:50,	reqs:{ 'control_system_development':1 },	},

	{	type:'item',	group:'sfy_component_8',	id:'turbo_motor',	name:'sfy_turbo_motor',	img:'/fgfactory/sfy/turbo_motor.png',	max:50,	reqs:{ 'leading_edge_production':1 },	},
	{	type:'item',	group:'sfy_component_8',	id:'pressure_conversion_cube',	name:'sfy_pressure_conversion_cube',	img:'/fgfactory/sfy/pressure_conversion_cube.png',	max:50,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'item',	group:'sfy_component_8',	id:'thermal_propulsion_rocket',	name:'sfy_thermal_propulsion_rocket',	img:'/fgfactory/sfy/thermal_propulsion_rocket.png',	max:50,	reqs:{ 'leading_edge_production':1 },	},
	{	type:'item',	group:'sfy_component_8',	id:'biochemical_sculptor',	name:'sfy_biochemical_sculptor',	img:'/fgfactory/sfy/biochemical_sculptor.png',	max:50,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component_8',	id:'ai_expansion_server',	name:'sfy_ai_expansion_server',	img:'/fgfactory/sfy/ai_expansion_server.png',	max:50,	reqs:{ 'quantum_encoding':1 },	},
	
	{	type:'item',	group:'sfy_component_9',	id:'nuclear_pasta',	name:'sfy_nuclear_pasta',	img:'/fgfactory/sfy/nuclear_pasta.png',	max:50,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'item',	group:'sfy_component_9',	id:'singularity_cell',	name:'sfy_singularity_cell',	img:'/fgfactory/sfy/singularity_cell.png',	max:50,	reqs:{ 'spatial_energy_regulation':1 },	},	
	{	type:'item',	group:'sfy_component_9',	id:'ballistic_warp_drive',	name:'sfy_ballistic_warp_drive',	img:'/fgfactory/sfy/ballistic_warp_drive.png',	max:50,	reqs:{ 'spatial_energy_regulation':1 },	},
	
	// MANUALS
	
	{	type:'manual',	id:'manual_hub_upgrade_1',	select:{ count:1, values:[ 1 ] },	results:{ 'hub_upgrade_1':1 },	costs:{ 'iron_rod':10 },	},		
	{	type:'manual',	id:'manual_hub_upgrade_2',	select:{ count:1, values:[ 1 ] },	results:{ 'hub_upgrade_2':1, 'energy':20e6 },	costs:{ 'iron_rod':20, 'iron_plate':10 },	},		
	{	type:'manual',	id:'manual_hub_upgrade_3',	select:{ count:1, values:[ 1 ] },	results:{ 'hub_upgrade_3':1 },	costs:{ 'iron_rod':20, 'iron_plate':20, 'wire':20 },	},		
	{	type:'manual',	id:'manual_hub_upgrade_5',	select:{ count:1, values:[ 1 ] },	results:{ 'hub_upgrade_5':1, 'energy':20e6 },	costs:{ 'iron_rod':75, 'cable':50, 'concrete':20 },	},		
	{	type:'manual',	id:'manual_hub_upgrade_6',	select:{ count:1, values:[ 1 ] },	results:{ 'hub_upgrade_6':1 },	costs:{ 'iron_rod':100, 'iron_plate':100, 'wire':100, 'concrete':50 },	},		
	
	{	type:'manual',	id:'manual_part_asssembly',	select:{ count:1, values:[ 1 ] },	results:{ 'part_asssembly':1 },	costs:{ 'cable':200, 'iron_rod':200, 'screw':500, 'iron_plate':300 },	},		
	{	type:'manual',	id:'manual_coal_power',	select:{ count:1, values:[ 1 ] },	results:{ 'coal_power':1 },	costs:{ 'reinforced_iron_plate':150, 'rotor':50, 'cable':500 },	},		
	{	type:'manual',	id:'manual_basic_steel_production',	select:{ count:1, values:[ 1 ] },	results:{ 'basic_steel_production':1 },	costs:{ 'modular_frame':50, 'rotor':150, 'concrete':500, 'wire':1000 },	},		
	{	type:'manual',	id:'manual_logistics',	select:{ count:1, values:[ 1 ] },	results:{ 'logistics':1 },	costs:{ 'steel_beam':200, 'steel_pipe':200, 'reinforced_iron_plate':400 },	},		
	{	type:'manual',	id:'manual_advanced_steel_production',	select:{ count:1, values:[ 1 ] },	results:{ 'advanced_steel_production':1 },	costs:{ 'steel_pipe':100, 'modular_frame':100, 'rotor':200, 'concrete':500 },	},		
	{	type:'manual',	id:'manual_oil_processing',	select:{ count:1, values:[ 1 ] },	results:{ 'oil_processing':1 },	costs:{ 'motor':50, 'encased_industrial_beam':100, 'steel_pipe':500, 'copper_sheet':500 },	},		
	{	type:'manual',	id:'manual_petroleum_power',	select:{ count:1, values:[ 1 ] },	results:{ 'petroleum_power':1 },	costs:{ 'motor':100, 'encased_industrial_beam':100, 'rubber':200, 'plastic':200 },	},		
	{	type:'manual',	id:'manual_industrial_manufacturing',	select:{ count:1, values:[ 1 ] },	results:{ 'industrial_manufacturing':1 },	costs:{ 'motor':200, 'modular_frame':200, 'plastic':400, 'cable':1000 },	},		
	{	type:'manual',	id:'manual_bauxite_refinement',	select:{ count:1, values:[ 1 ] },	results:{ 'bauxite_refinement':1 },	costs:{ 'computer':100, 'heavy_modular_frame':100, 'motor':200, 'rubber':500 },	},		
	{	type:'manual',	id:'manual_control_system_development',	select:{ count:1, values:[ 1 ] },	results:{ 'control_system_development':1 },	costs:{ 'alclad_aluminum_sheet':200, 'aluminum_casing':400, 'computer':200, 'plastic':1000 },	},		
	{	type:'manual',	id:'manual_nuclear_power',	select:{ count:1, values:[ 1 ] },	results:{ 'nuclear_power':1 },	costs:{ 'supercomputer':50, 'heavy_modular_frame':200, 'cable':1000, 'concrete':2000 },	},		
	{	type:'manual',	id:'manual_advanced_aluminum_production',	select:{ count:1, values:[ 1 ] },	results:{ 'advanced_aluminum_production':1 },	costs:{ 'radio_control_unit':50, 'aluminum_casing':200, 'alclad_aluminum_sheet':400, 'wire':3000 },	},		
	{	type:'manual',	id:'manual_leading_edge_production',	select:{ count:1, values:[ 1 ] },	results:{ 'leading_edge_production':1 },	costs:{ 'fused_modular_frame':50, 'supercomputer':100, 'steel_pipe':1000 },	},		
	{	type:'manual',	id:'manual_particle_enrichment',	select:{ count:1, values:[ 1 ] },	results:{ 'particle_enrichment':1 },	costs:{ 'turbo_motor':50, 'fused_modular_frame':100, 'cooling_system':200, 'quickwire':2500 },	},		
	{	type:'manual',	id:'manual_matter_conversion',	select:{ count:1, values:[ 1 ] },	results:{ 'matter_conversion':1 },	costs:{ 'fused_modular_frame':100, 'radio_control_unit':250, 'cooling_system':500, },	},		
	{	type:'manual',	id:'manual_quantum_encoding',	select:{ count:1, values:[ 1 ] },	results:{ 'quantum_encoding':1 },	costs:{ 'time_crystal':50, 'ficsite_trigon':100, 'turbo_motor':200, 'supercomputer':400 },	},		
	{	type:'manual',	id:'manual_spatial_energy_regulation',	select:{ count:1, values:[ 1 ] },	results:{ 'spatial_energy_regulation':1 },	costs:{ 'superposition_oscillator':100, 'turbo_motor':250, 'radio_control_unit':500, 'sam_fluctuator':1000 },	},		
									
	{	type:'manual',	id:'manual_phase_0',	select:{ count:1, values:[ 1 ] },	results:{ 'phase_0':1 },	costs:{ 'concrete':500, 'iron_plate':250, 'iron_rod':400, 'wire':1500 },	},		
	{	type:'manual',	id:'manual_phase_1',	select:{ count:1, values:[ 1 ] },	results:{ 'phase_1':1 },	costs:{ 'smart_plating':50 },	},		
	{	type:'manual',	id:'manual_phase_2',	select:{ count:1, values:[ 1 ] },	results:{ 'phase_2':1 },	costs:{ 'smart_plating':1000, 'versatile_framework':1000, 'automated_wiring':100 },	},		
	{	type:'manual',	id:'manual_phase_3',	select:{ count:1, values:[ 1 ] },	results:{ 'phase_3':1 },	costs:{ 'versatile_framework':2500, 'modular_engine':500, 'adaptive_control_unit':100 },	},		
	{	type:'manual',	id:'manual_phase_4',	select:{ count:1, values:[ 1 ] },	results:{ 'phase_4':1 },	costs:{ 'assembly_director_system':500, 'magnetic_field_generator':500, 'nuclear_pasta':100, 'thermal_propulsion_rocket':250 },	},		
	{	type:'manual',	id:'manual_phase_5',	select:{ count:1, values:[ 1 ] },	results:{ 'phase_5':1 },	costs:{ 'nuclear_pasta':1000, 'biochemical_sculptor':1000, 'ai_expansion_server':256, 'ballistic_warp_drive':200 },	},		
									
	{	type:'manual',	id:'manual_storage_container_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'storage_container_1':1 },	costs:{ 'iron_plate':10, 'iron_rod':10 },	},		
	{	type:'manual',	id:'manual_storage_container_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'storage_container_2':1 },	costs:{ 'steel_beam':20, 'steel_pipe':20 },	},		
	{	type:'manual',	id:'manual_fluid_buffer_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'fluid_buffer_1':1 },	costs:{ 'copper_sheet':10, 'modular_frame':5 },	},		
	{	type:'manual',	id:'manual_fluid_buffer_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'fluid_buffer_2':1 },	costs:{ 'encased_industrial_beam':5, 'copper_sheet':10, 'plastic':25 },	},		
									
	{	type:'manual',	id:'manual_biomass_burner',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'biomass_burner':1, 'energy':30e6 },	costs:{ 'iron_plate':15, 'iron_rod':15, 'wire':25 },	inputs:{ 'biomass':0.15 },	},	
	{	type:'manual',	id:'manual_coal_generator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'coal_generator':1, 'energy':75e6 },	costs:{ 'reinforced_iron_plate':20, 'rotor':10, 'cable':30 },	inputs:{ 'coal':0.25, 'water':0.75 },	},	
	{	type:'manual',	id:'manual_fuel_generator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'fuel_generator':1, 'energy':250e6 },	costs:{ 'motor':15, 'encased_industrial_beam':15, 'copper_sheet':30, 'rubber':50, 'quickwire':50 },	inputs:{ 'fuel':0.5 },	},	
	{	type:'manual',	id:'manual_nuclear_power_plant',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'nuclear_power_plant':1, 'energy':2500e6 },	costs:{ 'supercomputer':10, 'heavy_modular_frame':25, 'alclad_aluminum_sheet':100, 'cable':200, 'concrete':250 },	inputs:{ 'uranium_fuel_rod':0.01, 'water':4 },	},	
									
	{	type:'manual',	id:'manual_miner_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'miner_0':1 },	costs:{ 'iron_plate':2, 'iron_rod':4 },	},		
	{	type:'manual',	id:'manual_miner_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'miner_1':1 },	costs:{ 'iron_plate':10, 'concrete':10 },	upgrades:{ 'miner_0':1 },	},	
	{	type:'manual',	id:'manual_miner_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'miner_2':1 },	costs:{ 'encased_industrial_beam':10, 'steel_pipe':20, 'modular_frame':10 },	upgrades:{ 'miner_0':2 },	},	
	{	type:'manual',	id:'manual_miner_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'miner_3':1 },	costs:{ 'steel_pipe':50, 'supercomputer':5, 'fused_modular_frame':10, 'turbo_motor':3 },	upgrades:{ 'miner_0':3 },	},	
	{	type:'manual',	id:'manual_water_extractor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'water_extractor':1 },	costs:{ 'copper_sheet':20, 'reinforced_iron_plate':10, 'rotor':10 },	},		
	{	type:'manual',	id:'manual_oil_extractor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'oil_extractor':1 },	costs:{ 'motor':15, 'encased_industrial_beam':20, 'cable':60 },	},		
	{	type:'manual',	id:'manual_gas_extractor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'gas_extractor':1 },	costs:{ 'radio_control_unit':10, 'heavy_modular_frame':25, 'motor':50, 'alclad_aluminum_sheet':50, 'rubber':100, 'steel_beam':10, 'aluminum_casing':10 },	},		
									
	{	type:'manual',	id:'manual_smelter',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'smelter':1 },	costs:{ 'iron_rod':5, 'wire':8 },	},		
	{	type:'manual',	id:'manual_builder',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'builder':1 },	costs:{ 'reinforced_iron_plate':2, 'cable':8 },	},		
	{	type:'manual',	id:'manual_assembler',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'assembler':1 },	costs:{ 'reinforced_iron_plate':2, 'rotor':4, 'cable':10 },	},		
	{	type:'manual',	id:'manual_foundry',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'foundry':1 },	costs:{ 'modular_frame':10, 'rotor':10, 'concrete':20 },	},		
	{	type:'manual',	id:'manual_refinery',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'refinery':1 },	costs:{ 'motor':10, 'encased_industrial_beam':10, 'steel_pipe':30, 'copper_sheet':20 },	},		
	{	type:'manual',	id:'manual_manufacturer',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'manufacturer':1 },	costs:{ 'motor':10, 'modular_frame':20, 'plastic':50, 'cable':50 },	},		
	{	type:'manual',	id:'manual_blender',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'blender':1 },	costs:{ 'computer':10, 'heavy_modular_frame':10, 'motor':20, 'aluminum_casing':50 },	},		
	{	type:'manual',	id:'manual_particle_accelerator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'particle_accelerator':1 },	costs:{ 'turbo_motor':10, 'supercomputer':10, 'fused_modular_frame':25, 'cooling_system':50, 'quickwire':500 },	},		
	{	type:'manual',	id:'manual_converter',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'converter':1 },	costs:{ 'fused_modular_frame':10, 'cooling_system':25, 'radio_control_unit':50, 'sam_fluctuator':100 },	},		
	{	type:'manual',	id:'manual_quantum_encoder',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	results:{ 'quantum_encoder':1 },	costs:{ 'turbo_motor':20, 'supercomputer':20, 'cooling_system':50, 'time_crystal':50, 'ficsite_trigon':100 },	},		
									
	{	type:'manual',	id:'manual_iron_ore',	select:{ count:1, values:[ 1 ] },	results:{ 'iron_ore':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_copper_ore',	select:{ count:1, values:[ 1 ] },	results:{ 'copper_ore':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_limestone',	select:{ count:1, values:[ 1 ] },	results:{ 'limestone':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_coal',	select:{ count:1, values:[ 1 ] },	results:{ 'coal':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_caterium_ore',	select:{ count:1, values:[ 1 ] },	results:{ 'caterium_ore':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_bauxite',	select:{ count:1, values:[ 1 ] },	results:{ 'bauxite':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_raw_quartz',	select:{ count:1, values:[ 1 ] },	results:{ 'raw_quartz':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_sulfur',	select:{ count:1, values:[ 1 ] },	results:{ 'sulfur':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_uranium',	select:{ count:1, values:[ 1 ] },	results:{ 'uranium':1 },	status:'waiting',	seconds:2,	},	
	{	type:'manual',	id:'manual_sam',	select:{ count:1, values:[ 1 ] },	results:{ 'sam':1 },	status:'waiting',	seconds:2,	},	
									
	{	type:'manual',	id:'manual_iron_ingot',	select:{ count:1, values:[ 1 ] },	results:{ 'iron_ingot':1 },	status:'waiting',	seconds:0.75,	costs:{ 'iron_ore':1 },	},
	{	type:'manual',	id:'manual_copper_ingot',	select:{ count:1, values:[ 1 ] },	results:{ 'copper_ingot':1 },	status:'waiting',	seconds:0.75,	costs:{ 'copper_ore':1 },	},
	{	type:'manual',	id:'manual_concrete',	select:{ count:1, values:[ 1 ] },	results:{ 'concrete':1 },	status:'waiting',	seconds:0.5,	costs:{ 'limestone':3 },	},
	{	type:'manual',	id:'manual_ai_limiter',	select:{ count:1, values:[ 1 ] },	results:{ 'ai_limiter':1 },	status:'waiting',	seconds:1.5,	costs:{ 'copper_sheet':5, 'quickwire':20 },	},
	{	type:'manual',	id:'manual_alclad_aluminum_sheet',	select:{ count:1, values:[ 1 ] },	results:{ 'alclad_aluminum_sheet':3 },	status:'waiting',	seconds:1.5,	costs:{ 'aluminum_ingot':3, 'copper_ingot':1 },	},
	{	type:'manual',	id:'manual_aluminum_casing',	select:{ count:1, values:[ 1 ] },	results:{ 'aluminum_casing':2 },	status:'waiting',	seconds:0.5,	costs:{ 'aluminum_ingot':3 },	},
	{	type:'manual',	id:'manual_aluminum_ingot',	select:{ count:1, values:[ 1 ] },	results:{ 'aluminum_ingot':4 },	status:'waiting',	seconds:1.5,	costs:{ 'aluminum_scrap':6, 'silica':5 },	},
	{	type:'manual',	id:'manual_cable',	select:{ count:1, values:[ 1 ] },	results:{ 'cable':1 },	status:'waiting',	seconds:0.25,	costs:{ 'wire':2 },	},
	{	type:'manual',	id:'manual_caterium_ingot',	select:{ count:1, values:[ 1 ] },	results:{ 'caterium_ingot':1 },	status:'waiting',	seconds:1,	costs:{ 'caterium_ore':3 },	},
	{	type:'manual',	id:'manual_circuit_board',	select:{ count:1, values:[ 1 ] },	results:{ 'circuit_board':1 },	status:'waiting',	seconds:1.5,	costs:{ 'copper_sheet':2, 'plastic':4 },	},
	{	type:'manual',	id:'manual_computer',	select:{ count:1, values:[ 1 ] },	results:{ 'computer':1 },	status:'waiting',	seconds:4.5,	costs:{ 'circuit_board':4, 'cable':8, 'plastic':16 },	},
	{	type:'manual',	id:'manual_copper_powder',	select:{ count:1, values:[ 1 ] },	results:{ 'copper_powder':5 },	status:'waiting',	seconds:0.75,	costs:{ 'copper_ingot':30 },	},
	{	type:'manual',	id:'manual_copper_sheet',	select:{ count:1, values:[ 1 ] },	results:{ 'copper_sheet':1 },	status:'waiting',	seconds:0.75,	costs:{ 'copper_ingot':2 },	},
	{	type:'manual',	id:'manual_crystal_oscillator',	select:{ count:1, values:[ 1 ] },	results:{ 'crystal_oscillator':2 },	status:'waiting',	seconds:4.5,	costs:{ 'quartz_crystal':36, 'cable':28, 'reinforced_iron_plate':5 },	},
	{	type:'manual',	id:'manual_electromagnetic_control_rod',	select:{ count:1, values:[ 1 ] },	results:{ 'electromagnetic_control_rod':2 },	status:'waiting',	seconds:3.75,	costs:{ 'stator':3, 'ai_limiter':2 },	},
	{	type:'manual',	id:'manual_encased_industrial_beam',	select:{ count:1, values:[ 1 ] },	results:{ 'encased_industrial_beam':1 },	status:'waiting',	seconds:1.25,	costs:{ 'steel_beam':3, 'concrete':6 },	},
	{	type:'manual',	id:'manual_ficsite_trigon',	select:{ count:1, values:[ 1 ] },	results:{ 'ficsite_trigon':3 },	status:'waiting',	seconds:0.75,	costs:{ 'ficsite_ingot':1 },	},
	{	type:'manual',	id:'manual_heat_sink',	select:{ count:1, values:[ 1 ] },	results:{ 'heat_sink':1 },	status:'waiting',	seconds:1.5,	costs:{ 'alclad_aluminum_sheet':5, 'copper_sheet':3 },	},
	{	type:'manual',	id:'manual_heavy_modular_frame',	select:{ count:1, values:[ 1 ] },	results:{ 'heavy_modular_frame':1 },	status:'waiting',	seconds:2.25,	costs:{ 'modular_frame':5, 'steel_pipe':20, 'encased_industrial_beam':5 },	},
	{	type:'manual',	id:'manual_high_speed_connector',	select:{ count:1, values:[ 1 ] },	results:{ 'high_speed_connector':1 },	status:'waiting',	seconds:2,	costs:{ 'quickwire':56, 'cable':10, 'circuit_board':1 },	},
	{	type:'manual',	id:'manual_iron_plate',	select:{ count:1, values:[ 1 ] },	results:{ 'iron_plate':2 },	status:'waiting',	seconds:0.75,	costs:{ 'iron_ingot':3 },	},
	{	type:'manual',	id:'manual_iron_rod',	select:{ count:1, values:[ 1 ] },	results:{ 'iron_rod':1 },	status:'waiting',	seconds:0.25,	costs:{ 'iron_ingot':1 },	},
	{	type:'manual',	id:'manual_modular_frame',	select:{ count:1, values:[ 1 ] },	results:{ 'modular_frame':2 },	status:'waiting',	seconds:3.75,	costs:{ 'reinforced_iron_plate':3, 'iron_rod':12 },	},
	{	type:'manual',	id:'manual_motor',	select:{ count:1, values:[ 1 ] },	results:{ 'motor':1 },	status:'waiting',	seconds:3,	costs:{ 'rotor':2, 'stator':2 },	},
	{	type:'manual',	id:'manual_pressure_conversion_cube',	select:{ count:1, values:[ 1 ] },	results:{ 'pressure_conversion_cube':1 },	status:'waiting',	seconds:15,	costs:{ 'fused_modular_frame':1, 'radio_control_unit':2 },	},
	{	type:'manual',	id:'manual_quartz_crystal',	select:{ count:1, values:[ 1 ] },	results:{ 'quartz_crystal':3 },	status:'waiting',	seconds:2,	costs:{ 'raw_quartz':5 },	},
	{	type:'manual',	id:'manual_quickwire',	select:{ count:1, values:[ 1 ] },	results:{ 'quickwire':5 },	status:'waiting',	seconds:1.25,	costs:{ 'caterium_ingot':1 },	},
	{	type:'manual',	id:'manual_radio_control_unit',	select:{ count:1, values:[ 1 ] },	results:{ 'radio_control_unit':2 },	status:'waiting',	seconds:6,	costs:{ 'aluminum_casing':32, 'crystal_oscillator':1, 'computer':2 },	},
	{	type:'manual',	id:'manual_reanimated_sam',	select:{ count:1, values:[ 1 ] },	results:{ 'reanimated_sam':1 },	status:'waiting',	seconds:0.25,	costs:{ 'sam':4 },	},
	{	type:'manual',	id:'manual_reinforced_iron_plate',	select:{ count:1, values:[ 1 ] },	results:{ 'reinforced_iron_plate':1 },	status:'waiting',	seconds:1.5,	costs:{ 'iron_plate':6, 'screw':12 },	},
	{	type:'manual',	id:'manual_rotor',	select:{ count:1, values:[ 1 ] },	results:{ 'rotor':1 },	status:'waiting',	seconds:1.5,	costs:{ 'iron_rod':5, 'screw':25 },	},
	{	type:'manual',	id:'manual_sam_fluctuator',	select:{ count:1, values:[ 1 ] },	results:{ 'sam_fluctuator':1 },	status:'waiting',	seconds:0.75,	costs:{ 'reanimated_sam':6, 'wire':5, 'steel_pipe':3 },	},
	{	type:'manual',	id:'manual_screw',	select:{ count:1, values:[ 1 ] },	results:{ 'screw':4 },	status:'waiting',	seconds:0.75,	costs:{ 'iron_rod':1 },	},
	{	type:'manual',	id:'manual_silica',	select:{ count:1, values:[ 1 ] },	results:{ 'silica':5 },	status:'waiting',	seconds:2,	costs:{ 'raw_quartz':3 },	},
	{	type:'manual',	id:'manual_stator',	select:{ count:1, values:[ 1 ] },	results:{ 'stator':1 },	status:'waiting',	seconds:2.25,	costs:{ 'steel_pipe':3, 'wire':8 },	},
	{	type:'manual',	id:'manual_steel_beam',	select:{ count:1, values:[ 1 ] },	results:{ 'steel_beam':1 },	status:'waiting',	seconds:0.5,	costs:{ 'steel_ingot':4 },	},
	{	type:'manual',	id:'manual_steel_ingot',	select:{ count:1, values:[ 1 ] },	results:{ 'steel_ingot':3 },	status:'waiting',	seconds:1.5,	costs:{ 'iron_ore':3, 'coal':3 },	},
	{	type:'manual',	id:'manual_steel_pipe',	select:{ count:1, values:[ 1 ] },	results:{ 'steel_pipe':2 },	status:'waiting',	seconds:0.75,	costs:{ 'steel_ingot':3 },	},
	{	type:'manual',	id:'manual_supercomputer',	select:{ count:1, values:[ 1 ] },	results:{ 'supercomputer':1 },	status:'waiting',	seconds:6,	costs:{ 'computer':4, 'ai_limiter':2, 'high_speed_connector':3, 'plastic':28 },	},
	{	type:'manual',	id:'manual_turbo_motor',	select:{ count:1, values:[ 1 ] },	results:{ 'turbo_motor':1 },	status:'waiting',	seconds:8,	costs:{ 'cooling_system':4, 'radio_control_unit':2, 'motor':4 },	},
	{	type:'manual',	id:'manual_wire',	select:{ count:1, values:[ 1 ] },	results:{ 'wire':2 },	status:'waiting',	seconds:0.5,	costs:{ 'copper_ingot':1 },	},
	
	// STORERS

	{	type:'storer',	id:'storer_iron_ore_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_ore':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_copper_ore_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_ore':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_limestone_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'limestone':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_biomass_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'biomass':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_coal_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'coal':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_caterium_ore_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'caterium_ore':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_bauxite_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'bauxite':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_raw_quartz_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'raw_quartz':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_sulfur_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sulfur':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_uranium_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'uranium':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_sam_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sam':100 },	assign:{ id:'storage_container_1' },	},
							
	{	type:'storer',	id:'storer_iron_ingot_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_ingot':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_copper_ingot_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_ingot':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_concrete_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'concrete':500 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_plastic_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'plastic':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_rubber_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'rubber':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_caterium_ingot_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'caterium_ingot':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_steel_ingot_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'steel_ingot':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_aluminum_ingot_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'aluminum_ingot':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_quartz_crystal_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'quartz_crystal':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_silica_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'silica':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_ficsite_ingot_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ficsite_ingot':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_diamonds_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'diamonds':200 },	assign:{ id:'storage_container_1' },	},
							
	{	type:'storer',	id:'storer_iron_rod_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_rod':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_iron_plate_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_plate':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_wire_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'wire':500 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_cable_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'cable':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_screw_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'screw':500 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_reinforced_iron_plate_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'reinforced_iron_plate':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_copper_sheet_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_sheet':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_rotor_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'rotor':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_modular_frame_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'modular_frame':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_steel_beam_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'steel_beam':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_steel_pipe_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'steel_pipe':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_encased_industrial_beam_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'encased_industrial_beam':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_stator_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'stator':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_motor_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'motor':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_circuit_board_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'circuit_board':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_quickwire_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'quickwire':500 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_computer_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'computer':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_heavy_modular_frame_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'heavy_modular_frame':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_aluminum_scrap_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'aluminum_scrap':500 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_alclad_aluminum_sheet_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'alclad_aluminum_sheet':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_aluminum_casing_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'aluminum_casing':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_ai_limiter_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ai_limiter':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_crystal_oscillator_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'crystal_oscillator':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_radio_control_unit_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'radio_control_unit':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_high_speed_connector_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'high_speed_connector':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_battery_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'battery':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_supercomputer_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'supercomputer':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_encased_uranium_cell_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'encased_uranium_cell':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_electromagnetic_control_rod_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'electromagnetic_control_rod':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_uranium_fuel_rod_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'uranium_fuel_rod':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_heat_sink_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'heat_sink':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_cooling_system_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'cooling_system':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_fused_modular_frame_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'fused_modular_frame':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_turbo_motor_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'turbo_motor':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_copper_powder_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_powder':500 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_pressure_conversion_cube_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'pressure_conversion_cube':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_time_crystal_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'time_crystal':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_ficsite_trigon_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ficsite_trigon':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_reanimated_sam_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'reanimated_sam':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_sam_fluctuator_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sam_fluctuator':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_dark_matter_crystal_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'dark_matter_crystal':200 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_superposition_oscillator_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'superposition_oscillator':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_neural_quantum_processor_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'neural_quantum_processor':100 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_singularity_cell_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'singularity_cell':50 },	assign:{ id:'storage_container_1' },	},
							
	{	type:'storer',	id:'storer_smart_plating_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'smart_plating':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_versatile_framework_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'versatile_framework':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_automated_wiring_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'automated_wiring':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_modular_engine_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'modular_engine':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_adaptive_control_unit_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'adaptive_control_unit':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_assembly_director_system_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'assembly_director_system':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_magnetic_field_generator_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'magnetic_field_generator':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_nuclear_pasta_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'nuclear_pasta':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_thermal_propulsion_rocket_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'thermal_propulsion_rocket':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_biochemical_sculptor_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'biochemical_sculptor':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_ai_expansion_server_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ai_expansion_server':50 },	assign:{ id:'storage_container_1' },	},
	{	type:'storer',	id:'storer_ballistic_warp_drive_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ballistic_warp_drive':50 },	assign:{ id:'storage_container_1' },	},
							
	{	type:'storer',	id:'storer_iron_ore_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_ore':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_copper_ore_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_ore':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_limestone_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'limestone':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_biomass_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'biomass':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_coal_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'coal':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_caterium_ore_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'caterium_ore':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_bauxite_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'bauxite':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_raw_quartz_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'raw_quartz':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_sulfur_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sulfur':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_uranium_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'uranium':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_sam_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sam':200 },	assign:{ id:'storage_container_2' },	},
							
	{	type:'storer',	id:'storer_iron_ingot_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_ingot':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_copper_ingot_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_ingot':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_concrete_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'concrete':1000 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_plastic_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'plastic':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_rubber_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'rubber':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_caterium_ingot_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'caterium_ingot':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_steel_ingot_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'steel_ingot':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_aluminum_ingot_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'aluminum_ingot':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_quartz_crystal_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'quartz_crystal':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_silica_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'silica':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_ficsite_ingot_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ficsite_ingot':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_diamonds_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'diamonds':200 },	assign:{ id:'storage_container_2' },	},
							
	{	type:'storer',	id:'storer_iron_rod_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_rod':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_iron_plate_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'iron_plate':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_wire_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'wire':1000 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_cable_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'cable':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_screw_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'screw':1000 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_reinforced_iron_plate_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'reinforced_iron_plate':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_copper_sheet_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_sheet':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_rotor_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'rotor':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_modular_frame_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'modular_frame':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_steel_beam_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'steel_beam':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_steel_pipe_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'steel_pipe':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_encased_industrial_beam_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'encased_industrial_beam':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_stator_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'stator':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_motor_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'motor':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_circuit_board_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'circuit_board':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_quickwire_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'quickwire':1000 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_computer_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'computer':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_heavy_modular_frame_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'heavy_modular_frame':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_aluminum_scrap_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'aluminum_scrap':1000 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_alclad_aluminum_sheet_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'alclad_aluminum_sheet':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_aluminum_casing_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'aluminum_casing':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_ai_limiter_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ai_limiter':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_crystal_oscillator_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'crystal_oscillator':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_radio_control_unit_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'radio_control_unit':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_high_speed_connector_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'high_speed_connector':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_battery_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'battery':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_supercomputer_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'supercomputer':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_encased_uranium_cell_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'encased_uranium_cell':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_electromagnetic_control_rod_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'electromagnetic_control_rod':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_uranium_fuel_rod_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'uranium_fuel_rod':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_heat_sink_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'heat_sink':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_cooling_system_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'cooling_system':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_fused_modular_frame_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'fused_modular_frame':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_turbo_motor_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'turbo_motor':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_copper_powder_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'copper_powder':1000 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_pressure_conversion_cube_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'pressure_conversion_cube':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_time_crystal_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'time_crystal':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_ficsite_trigon_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ficsite_trigon':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_reanimated_sam_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'reanimated_sam':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_sam_fluctuator_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sam_fluctuator':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_dark_matter_crystal_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'dark_matter_crystal':400 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_superposition_oscillator_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'superposition_oscillator':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_neural_quantum_processor_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'neural_quantum_processor':200 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_singularity_cell_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'singularity_cell':100 },	assign:{ id:'storage_container_2' },	},
							
	{	type:'storer',	id:'storer_smart_plating_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'smart_plating':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_versatile_framework_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'versatile_framework':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_automated_wiring_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'automated_wiring':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_modular_engine_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'modular_engine':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_adaptive_control_unit_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'adaptive_control_unit':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_assembly_director_system_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'assembly_director_system':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_magnetic_field_generator_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'magnetic_field_generator':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_nuclear_pasta_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'nuclear_pasta':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_thermal_propulsion_rocket_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'thermal_propulsion_rocket':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_biochemical_sculptor_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'biochemical_sculptor':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_ai_expansion_server_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ai_expansion_server':100 },	assign:{ id:'storage_container_2' },	},
	{	type:'storer',	id:'storer_ballistic_warp_drive_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'ballistic_warp_drive':100 },	assign:{ id:'storage_container_2' },	},
							
	{	type:'storer',	id:'storer_water_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'water':400 },	assign:{ id:'fluid_buffer_1' },	},
	{	type:'storer',	id:'storer_crude_oil_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'crude_oil':400 },	assign:{ id:'fluid_buffer_1' },	},
	{	type:'storer',	id:'storer_nitrogen_gas_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'nitrogen_gas':400 },	assign:{ id:'fluid_buffer_1' },	},
	{	type:'storer',	id:'storer_fuel_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'fuel':400 },	assign:{ id:'fluid_buffer_1' },	},
	{	type:'storer',	id:'storer_alumina_solution_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'alumina_solution':400 },	assign:{ id:'fluid_buffer_1' },	},
	{	type:'storer',	id:'storer_sulfuric_acid_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sulfuric_acid':400 },	assign:{ id:'fluid_buffer_1' },	},
	{	type:'storer',	id:'storer_dark_matter_residue_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'dark_matter_residue':400 },	assign:{ id:'fluid_buffer_1' },	},
	{	type:'storer',	id:'storer_excited_photonic_matter_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'excited_photonic_matter':400 },	assign:{ id:'fluid_buffer_1' },	},
							
	{	type:'storer',	id:'storer_water_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'water':800 },	assign:{ id:'fluid_buffer_2' },	},
	{	type:'storer',	id:'storer_crude_oil_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'crude_oil':800 },	assign:{ id:'fluid_buffer_2' },	},
	{	type:'storer',	id:'storer_nitrogen_gas_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'nitrogen_gas':800 },	assign:{ id:'fluid_buffer_2' },	},
	{	type:'storer',	id:'storer_fuel_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'fuel':800 },	assign:{ id:'fluid_buffer_2' },	},
	{	type:'storer',	id:'storer_alumina_solution_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'alumina_solution':800 },	assign:{ id:'fluid_buffer_2' },	},
	{	type:'storer',	id:'storer_sulfuric_acid_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'sulfuric_acid':800 },	assign:{ id:'fluid_buffer_2' },	},
	{	type:'storer',	id:'storer_dark_matter_residue_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'dark_matter_residue':800 },	assign:{ id:'fluid_buffer_2' },	},
	{	type:'storer',	id:'storer_excited_photonic_matter_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	storages:{ 'excited_photonic_matter':800 },	assign:{ id:'fluid_buffer_2' },	},
	
	// PRODUCERS

	{	type:'producer',	id:'producer_iron_ore_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'iron_ore':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_copper_ore_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'copper_ore':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_limestone_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'limestone':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_biomass_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'biomass':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_coal_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'coal':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_caterium_ore_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'caterium_ore':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_bauxite_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'bauxite':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_raw_quartz_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'raw_quartz':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_sulfur_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sulfur':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_uranium_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'uranium':0.5 },	assign:{ id:'miner_0' },	},		
	{	type:'producer',	id:'producer_sam_0',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sam':0.5 },	assign:{ id:'miner_0' },	},		
									
	{	type:'producer',	id:'producer_iron_ore_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'iron_ore':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_copper_ore_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'copper_ore':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_limestone_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'limestone':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_biomass_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'biomass':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_coal_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'coal':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_caterium_ore_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'caterium_ore':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_bauxite_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'bauxite':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_raw_quartz_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'raw_quartz':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_sulfur_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sulfur':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_uranium_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'uranium':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
	{	type:'producer',	id:'producer_sam_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sam':1 },	assign:{ id:'miner_1' },	costs:{ 'energy':5e6 },	},	
									
	{	type:'producer',	id:'producer_iron_ore_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'iron_ore':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_copper_ore_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'copper_ore':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_limestone_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'limestone':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_biomass_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'biomass':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_coal_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'coal':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_caterium_ore_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'caterium_ore':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_bauxite_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'bauxite':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_raw_quartz_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'raw_quartz':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_sulfur_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sulfur':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_uranium_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'uranium':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
	{	type:'producer',	id:'producer_sam_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sam':2 },	assign:{ id:'miner_2' },	costs:{ 'energy':15e6 },	},	
									
	{	type:'producer',	id:'producer_iron_ore_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'iron_ore':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_copper_ore_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'copper_ore':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_limestone_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'limestone':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_biomass_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'biomass':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_coal_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'coal':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_caterium_ore_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'caterium_ore':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_bauxite_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'bauxite':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_raw_quartz_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'raw_quartz':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_sulfur_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sulfur':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_uranium_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'uranium':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
	{	type:'producer',	id:'producer_sam_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sam':4 },	assign:{ id:'miner_3' },	costs:{ 'energy':45e6 },	},	
									
	{	type:'producer',	id:'producer_water',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'water':2 },	assign:{ id:'water_extractor' },	costs:{ 'energy':20e6 },	},	
									
	{	type:'producer',	id:'producer_crude_oil',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'crude_oil':1 },	assign:{ id:'oil_extractor' },	costs:{ 'energy':40e6 },	},	
									
	{	type:'producer',	id:'producer_nitrogen_gas',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'nitrogen_gas':1 },	assign:{ id:'gas_extractor' },	costs:{ 'energy':150e6 },	},	
									
	{	type:'producer',	id:'producer_iron_ingot',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'iron_ingot':0.5 },	assign:{ id:'smelter' },	costs:{ 'energy':4e6 },	inputs:{ 'iron_ore':0.5 },	},
	{	type:'producer',	id:'producer_copper_ingot',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'copper_ingot':0.5 },	assign:{ id:'smelter' },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ore':0.5 },	},
	{	type:'producer',	id:'producer_caterium_ingot',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'caterium_ingot':0.5 },	assign:{ id:'smelter' },	costs:{ 'energy':4e6 },	inputs:{ 'caterium_ore':0.5 },	},
									
	{	type:'producer',	id:'producer_aluminum_casing',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'aluminum_casing':1 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'aluminum_ingot':1.5 },	},
	{	type:'producer',	id:'producer_cable',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'cable':0.5 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'wire':1 },	},
	{	type:'producer',	id:'producer_concrete',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'concrete':0.25 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'limestone':0.75 },	},
	{	type:'producer',	id:'producer_copper_powder',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'copper_powder':0.75 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ingot':5 },	},
	{	type:'producer',	id:'producer_copper_sheet',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'copper_sheet':0.25 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ingot':0.5 },	},
	{	type:'producer',	id:'producer_ficsite_trigon',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'ficsite_trigon':0.25 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'ficsite_ingot':0.75 },	},
	{	type:'producer',	id:'producer_iron_plate',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'iron_plate':0.25 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'iron_ingot':0.5 },	},
	{	type:'producer',	id:'producer_iron_rode',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'iron_rod':0.25 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'iron_ingot':0.25 },	},
	{	type:'producer',	id:'producer_quickwire',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'quickwire':1 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'caterium_ingot':0.2 },	},
	{	type:'producer',	id:'producer_reanimated_sam',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'reanimated_sam':0.5 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'sam':2 },	},
	{	type:'producer',	id:'producer_screw',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'screw':0.8 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'iron_rod':0.2 },	},
	{	type:'producer',	id:'producer_steel_beam',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'steel_beam':0.25 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'steel_ingot':1 },	},
	{	type:'producer',	id:'producer_steel_pipe',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'steel_pipe':0.2 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'steel_ingot':0.3 },	},
	{	type:'producer',	id:'producer_wire',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'wire':0.5 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ingot':0.25 },	},
	{	type:'producer',	id:'producer_quartz_crystal',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'quartz_crystal':0.37 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'raw_quartz':0.62 },	},
	{	type:'producer',	id:'producer_silica',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'silica':0.62 },	assign:{ id:'builder' },	costs:{ 'energy':4e6 },	inputs:{ 'raw_quartz':0.37 },	},
									
	{	type:'producer',	id:'producer_ai_limiter',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'ai_limiter':0.08 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'copper_sheet':0.42, 'quickwire':1.67 },	},
	{	type:'producer',	id:'producer_alclad_aluminum_sheet',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'alclad_aluminum_sheet':0.5 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'aluminum_ingot':0.5, 'copper_ingot':0.17 },	},
	{	type:'producer',	id:'producer_assembly_director_system',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'assembly_director_system':0.01 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'adaptive_control_unit':0.02, 'supercomputer':0.01 },	},
	{	type:'producer',	id:'producer_automated_wiring',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'automated_wiring':0.04 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'stator':0.04, 'cable':0.83 },	},
	{	type:'producer',	id:'producer_circuit_board',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'circuit_board':0.12 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'copper_sheet':0.25, 'plastic':0.5 },	},
	{	type:'producer',	id:'producer_electromagnetic_control_rod',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'electromagnetic_control_rod':0.07 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'stator':0.1, 'ai_limiter':0.07 },	},
	{	type:'producer',	id:'producer_encased_industrial_beam',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'encased_industrial_beam':0.1 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'steel_beam':0.3, 'concrete':0.6 },	},
	{	type:'producer',	id:'producer_heat_sink',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'heat_sink':0.12 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'alclad_aluminum_sheet':0.62, 'copper_sheet':0.37 },	},
	{	type:'producer',	id:'producer_magnetic_field_generator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'magnetic_field_generator':0.02 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'versatile_framework':0.04, 'electromagnetic_control_rod':0.02 },	},
	{	type:'producer',	id:'producer_modular_frame',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'modular_frame':0.03 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'reinforced_iron_plate':0.05, 'iron_rod':0.2 },	},
	{	type:'producer',	id:'producer_motor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'motor':0.08 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'rotor':0.17, 'stator':0.17 },	},
	{	type:'producer',	id:'producer_pressure_conversion_cube',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'pressure_conversion_cube':0.02 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'fused_modular_frame':0.02, 'radio_control_unit':0.03 },	},
	{	type:'producer',	id:'producer_reinforced_iron_plate',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'reinforced_iron_plate':0.08 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'iron_plate':0.5, 'screw':1 },	},
	{	type:'producer',	id:'producer_rotor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'rotor':0.07 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'iron_rod':0.33, 'screw':1.67 },	},
	{	type:'producer',	id:'producer_smart_plating',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'smart_plating':0.03 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'reinforced_iron_plate':0.03, 'rotor':0.03 },	},
	{	type:'producer',	id:'producer_stator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'stator':0.08 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'steel_pipe':0.25, 'wire':0.66 },	},
	{	type:'producer',	id:'producer_versatile_framework',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'versatile_framework':0.08 },	assign:{ id:'assembler' },	costs:{ 'energy':15e6 },	inputs:{ 'modular_frame':0.04, 'steel_beam':0.5 },	},
									
	{	type:'producer',	id:'producer_aluminum_ingot',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'aluminum_ingot':1 },	assign:{ id:'foundry' },	costs:{ 'energy':16e6 },	inputs:{ 'aluminum_scrap':1.5, 'silica':0.08 },	},
	{	type:'producer',	id:'producer_steel_ingot',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'steel_ingot':0.75 },	assign:{ id:'foundry' },	costs:{ 'energy':16e6 },	inputs:{ 'iron_ore':0.75, 'coal':0.75 },	},
									
	{	type:'producer',	id:'producer_alumina_solution',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'alumina_solution':2 },	assign:{ id:'refinery' },	costs:{ 'energy':30e6 },	inputs:{ 'bauxite':2, 'water':3 },	},
	{	type:'producer',	id:'producer_aluminum_scrap',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'aluminum_scrap':6 },	assign:{ id:'refinery' },	costs:{ 'energy':30e6 },	inputs:{ 'alumina_solution':4, 'coal':2 },	},
	{	type:'producer',	id:'producer_fuel',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'fuel':0.66 },	assign:{ id:'refinery' },	costs:{ 'energy':30e6 },	inputs:{ 'crude_oil':1 },	},
	{	type:'producer',	id:'producer_plastic',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'plastic':0.33 },	assign:{ id:'refinery' },	costs:{ 'energy':30e6 },	inputs:{ 'crude_oil':0.5 },	},
	{	type:'producer',	id:'producer_rubber',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'rubber':0.33 },	assign:{ id:'refinery' },	costs:{ 'energy':30e6 },	inputs:{ 'crude_oil':0.5 },	},
	{	type:'producer',	id:'producer_sulfuric_acid',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sulfuric_acid':0.83 },	assign:{ id:'refinery' },	costs:{ 'energy':30e6 },	inputs:{ 'sulfur':0.83, 'water':0.83 },	},
									
	{	type:'producer',	id:'producer_adaptive_control_unit',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'adaptive_control_unit':0.02 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'automated_wiring':0.08, 'circuit_board':0.08, 'heavy_modular_frame':0.02, 'computer':0.03 },	},
	{	type:'producer',	id:'producer_ballistic_warp_drive',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'ballistic_warp_drive':0.02 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'thermal_propulsion_rocket':0.02, 'singularity_cell':0.08, 'superposition_oscillator':0.03, 'dark_matter_crystal':0.66 },	},
	{	type:'producer',	id:'producer_computer',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'computer':0.04 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'circuit_board':0.17, 'cable':0.33, 'plastic':0.66 },	},
	{	type:'producer',	id:'producer_crystal_oscillator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'crystal_oscillator':0.02 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'quartz_crystal':0.3, 'cable':0.23, 'reinforced_iron_plate':0.04 },	},
	{	type:'producer',	id:'producer_heavy_modular_frame',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'heavy_modular_frame':0.03 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'modular_frame':0.17, 'steel_pipe':0.66, 'encased_industrial_beam':0.17, 'screw':4 },	},
	{	type:'producer',	id:'producer_high_speed_connector',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'high_speed_connector':0.06 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'quickwire':3.5, 'cable':0.62, 'circuit_board':0.06 },	},
	{	type:'producer',	id:'producer_modular_engine',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'modular_engine':0.02 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'motor':0.03, 'rubber':0.25, 'smart_plating':0.03 },	},
	{	type:'producer',	id:'producer_radio_control_unit',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'radio_control_unit':0.04 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'aluminum_casing':0.66, 'crystal_oscillator':0.02, 'computer':0.04 },	},
	{	type:'producer',	id:'producer_sam_fluctuator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'sam_fluctuator':0.17 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'reanimated_sam':1, 'wire':0.83, 'steel_pipe':0.5 },	},
	{	type:'producer',	id:'producer_singularity_cell',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'singularity_cell':0.17 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'nuclear_pasta':0.02, 'dark_matter_crystal':0.33, 'iron_plate':1.67, 'concrete':3.33 },	},
	{	type:'producer',	id:'producer_supercomputer',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'supercomputer':0.03 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'computer':0.12, 'ai_limiter':0.06, 'high_speed_connector':0.09, 'plastic':0.87 },	},
	{	type:'producer',	id:'producer_thermal_propulsion_rocket',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'thermal_propulsion_rocket':0.02 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'modular_engine':0.04, 'turbo_motor':0.02, 'cooling_system':0.05, 'fused_modular_frame':0.02 },	},
	{	type:'producer',	id:'producer_turbo_motor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'turbo_motor':0.03 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'cooling_system':0.12, 'radio_control_unit':0.06, 'motor':0.12, 'rubber':0.75 },	},
	{	type:'producer',	id:'producer_uranium_fuel_rod',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'uranium_fuel_rod':0.01 },	assign:{ id:'manufacturer' },	costs:{ 'energy':55e6 },	inputs:{ 'encased_uranium_cell':0.33, 'encased_industrial_beam':0.02, 'electromagnetic_control_rod':0.03 },	},
									
	{	type:'producer',	id:'producer_battery',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'battery':0.33 },	assign:{ id:'blender' },	costs:{ 'energy':75e6 },	inputs:{ 'sulfuric_acid':0.83, 'alumina_solution':0.66, 'aluminum_casing':0.33 },	},
	{	type:'producer',	id:'producer_biochemical_sculptor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'biochemical_sculptor':0.03 },	assign:{ id:'blender' },	costs:{ 'energy':75e6 },	inputs:{ 'assembly_director_system':0.01, 'ficsite_trigon':0.66, 'water':0.17 },	},
	{	type:'producer',	id:'producer_cooling_system',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'cooling_system':0.1 },	assign:{ id:'blender' },	costs:{ 'energy':75e6 },	inputs:{ 'heat_sink':0.2, 'rubber':0.2, 'water':0.5, 'nitrogen_gas':2.5 },	},
	{	type:'producer',	id:'producer_encased_uranium_cell',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'encased_uranium_cell':0.42 },	assign:{ id:'blender' },	costs:{ 'energy':75e6 },	inputs:{ 'uranium':0.83, 'concrete':0.25, 'sulfuric_acid':0.66 },	},
	{	type:'producer',	id:'producer_fused_modular_frame',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'fused_modular_frame':0.02 },	assign:{ id:'blender' },	costs:{ 'energy':75e6 },	inputs:{ 'heavy_modular_frame':0.02, 'aluminum_casing':1.25, 'nitrogen_gas':0.62 },	},
									
	{	type:'producer',	id:'producer_dark_matter_crystal',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'dark_matter_crystal':0.5 },	assign:{ id:'particle_accelerator' },	costs:{ 'energy':1000e6 },	inputs:{ 'diamonds':0.5, 'dark_matter_residue':2.5 },	},
	{	type:'producer',	id:'producer_diamonds',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'diamonds':0.5 },	assign:{ id:'particle_accelerator' },	costs:{ 'energy':1000e6 },	inputs:{ 'coal':10 },	},
	{	type:'producer',	id:'producer_nuclear_pasta',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'nuclear_pasta':0.01 },	assign:{ id:'particle_accelerator' },	costs:{ 'energy':1000e6 },	inputs:{ 'copper_powder':1.67, 'pressure_conversion_cube':0.01 },	},
									
	{	type:'producer',	id:'producer_ficsite_ingot_1',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'ficsite_ingot':0.5 },	assign:{ id:'converter' },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':1, 'aluminum_ingot':2 },	},
	{	type:'producer',	id:'producer_ficsite_ingot_2',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'ficsite_ingot':0.25 },	assign:{ id:'converter' },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':0.75, 'caterium_ingot':1 },	},
	{	type:'producer',	id:'producer_ficsite_ingot_3',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'ficsite_ingot':0.17 },	assign:{ id:'converter' },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':0.66, 'iron_ingot':4 },	},
	{	type:'producer',	id:'producer_time_crystal',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'time_crystal':0.1 },	assign:{ id:'converter' },	costs:{ 'energy':250e6 },	inputs:{ 'diamonds':0.2 },	},
	{	type:'producer',	id:'producer_dark_matter_residue',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'dark_matter_residue':1.67 },	assign:{ id:'converter' },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':0.83 },	},
	{	type:'producer',	id:'producer_excited_photonic_matter',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'excited_photonic_matter':3.33 },	assign:{ id:'converter' },	costs:{ 'energy':250e6 },	},	
									
	{	type:'producer',	id:'producer_ai_expansion_server',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'ai_expansion_server':0.07 },	assign:{ id:'quantum_encoder' },	costs:{ 'energy':1000e6 },	inputs:{ 'magnetic_field_generator':0.07, 'neural_quantum_processor':0.07, 'superposition_oscillator':0.07, 'excited_photonic_matter':1.67 },	},
	{	type:'producer',	id:'producer_neural_quantum_processor',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'neural_quantum_processor':0.05 },	assign:{ id:'quantum_encoder' },	costs:{ 'energy':1000e6 },	inputs:{ 'time_crystal':0.25, 'supercomputer':0.05, 'ficsite_trigon':0.75, 'excited_photonic_matter':1.25 },	},
	{	type:'producer',	id:'producer_superposition_oscillator',	select:{ count:1, values:[ 1, 5, 10, 25 ] },	outputs:{ 'superposition_oscillator':0.08 },	assign:{ id:'quantum_encoder' },	costs:{ 'energy':1000e6 },	inputs:{ 'dark_matter_crystal':0.5, 'crystal_oscillator':0.08, 'alclad_aluminum_sheet':0.75, 'excited_photonic_matter':2.08 },	},
]