const sfy_vanilla = {}
export default sfy_vanilla

sfy_vanilla.id = 'sfy_vanilla'
sfy_vanilla.title = 'sfy_vanilla_title'
sfy_vanilla.subtitle = 'sfy_vanilla_subtitle'
sfy_vanilla.desc = 'sfy_vanilla_desc'

sfy_vanilla.victoryReqs = { 'phase_5':1 }

sfy_vanilla.elems = [

	// MILESTONES
	
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_1',	name:'sfy_hub_upgrade_1',	count:0,	max:1,	},
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_2',	name:'sfy_hub_upgrade_2',	count:0,	max:1,	reqs:{ 'hub_upgrade_1':1 },	},
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_3',	name:'sfy_hub_upgrade_3',	count:0,	max:1,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_5',	name:'sfy_hub_upgrade_5',	count:0,	max:1,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'milestone',	group:'sfy_onboarding',	id:'hub_upgrade_6',	name:'sfy_hub_upgrade_6',	count:0,	max:1,	reqs:{ 'hub_upgrade_5':1 },	},
	
	{	type:'milestone',	group:'sfy_order',	id:'part_asssembly',	name:'sfy_part_asssembly',	count:0,	max:1,	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'coal_power',	name:'sfy_coal_power',	count:0,	max:1,	reqs:{ 'phase_1':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'basic_steel_production',	name:'sfy_basic_steel_production',	count:0,	max:1,	reqs:{ 'phase_1':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'logistics',	name:'sfy_logistics',	count:0,	max:1,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'advanced_steel_production',	name:'sfy_advanced_steel_production',	count:0,	max:1,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'oil_processing',	name:'sfy_oil_processing',	count:0,	max:1,	reqs:{ 'phase_2':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'petroleum_power',	name:'sfy_petroleum_power',	count:0,	max:1,	reqs:{ 'oil_processing':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'industrial_manufacturing',	name:'sfy_industrial_manufacturing',	count:0,	max:1,	reqs:{ 'oil_processing':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'bauxite_refinement',	name:'sfy_bauxite_refinement',	count:0,	max:1,	reqs:{ 'phase_3':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'control_system_development',	name:'sfy_control_system_development',	count:0,	max:1,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'nuclear_power',	name:'sfy_nuclear_power',	count:0,	max:1,	reqs:{ 'control_system_development':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'advanced_aluminum_production',	name:'sfy_advanced_aluminum_production',	count:0,	max:1,	reqs:{ 'control_system_development':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'leading_edge_production',	name:'sfy_leading_edge_production',	count:0,	max:1,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'particle_enrichment',	name:'sfy_particle_enrichment',	count:0,	max:1,	reqs:{ 'leading_edge_production':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'matter_conversion',	name:'sfy_matter_conversion',	count:0,	max:1,	reqs:{ 'phase_4':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'quantum_encoding',	name:'sfy_quantum_encoding',	count:0,	max:1,	reqs:{ 'matter_conversion':1 },	},
	{	type:'milestone',	group:'sfy_order',	id:'spatial_energy_regulation',	name:'sfy_spatial_energy_regulation',	count:0,	max:1,	reqs:{ 'quantum_encoding':1 },	},
	
	{	type:'milestone',	group:'sfy_project',	id:'phase_0',	name:'sfy_phase_0',	count:0,	max:1,	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_1',	name:'sfy_phase_1',	count:0,	max:1,	reqs:{ 'part_asssembly':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_2',	name:'sfy_phase_2',	count:0,	max:1,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_3',	name:'sfy_phase_3',	count:0,	max:1,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_4',	name:'sfy_phase_4',	count:0,	max:1,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'milestone',	group:'sfy_project',	id:'phase_5',	name:'sfy_phase_5',	count:0,	max:1,	reqs:{ 'spatial_energy_regulation':1 },	},
	
	// ENERGY
	
	{	type:'power',	id:'energy',	name:'sfy_energy',	img:'/fgfactory/sfy/energy.png',	count:0,	reqs:{ 'hub_upgrade_2':1 },	},
	
	// BUILDINGS
	
	{	type:'building',	group:'sfy_generator',	id:'biomass_burner',	name:'sfy_biomass_burner',	img:'/fgfactory/sfy/biomass_burner.png',	count:0,	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'building',	group:'sfy_generator',	id:'coal_generator',	name:'sfy_coal_generator',	img:'/fgfactory/sfy/coal_generator.png',	count:0,	reqs:{ 'coal_power':1 },	},
	{	type:'building',	group:'sfy_generator',	id:'fuel_generator',	name:'sfy_fuel_generator',	img:'/fgfactory/sfy/fuel_generator.png',	count:0,	reqs:{ 'petroleum_power':1 },	},
	{	type:'building',	group:'sfy_generator',	id:'nuclear_power_plant',	name:'sfy_nuclear_power_plant',	img:'/fgfactory/sfy/nuclear_power_plant.png',	count:0,	reqs:{ 'nuclear_power':1 },	},
	
	{	type:'building',	group:'sfy_container',	id:'storage_container_1',	name:'sfy_storage_container_1',	img:'/fgfactory/sfy/storage_container_1.png',	count:0,	reqs:{ 'hub_upgrade_5':1 },	},
	{	type:'building',	group:'sfy_container',	id:'storage_container_2',	name:'sfy_storage_container_2',	img:'/fgfactory/sfy/storage_container_2.png',	count:0,	reqs:{ 'logistics':1 },	},	
	{	type:'building',	group:'sfy_container',	id:'fluid_buffer_1',	name:'sfy_fluid_buffer_1',	img:'/fgfactory/sfy/fluid_buffer_1.png',	count:0,	reqs:{ 'coal_power':1 },	},
	{	type:'building',	group:'sfy_container',	id:'fluid_buffer_2',	name:'sfy_fluid_buffer_2',	img:'/fgfactory/sfy/fluid_buffer_2.png',	count:0,	reqs:{ 'petroleum_power':1 },	},	
	
	{	type:'building',	group:'sfy_extractor',	id:'miner_0',	name:'sfy_miner_0',	img:'/fgfactory/sfy/miner_0.png',	count:0,	reqs:{ 'hub_upgrade_1':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'miner_1',	name:'sfy_miner_1',	img:'/fgfactory/sfy/miner_1.png',	count:0,	reqs:{ 'hub_upgrade_5':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'miner_2',	name:'sfy_miner_2',	img:'/fgfactory/sfy/miner_2.png',	count:0,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'miner_3',	name:'sfy_miner_3',	img:'/fgfactory/sfy/miner_3.png',	count:0,	reqs:{ 'leading_edge_production':1 },	},	
	{	type:'building',	group:'sfy_extractor',	id:'water_extractor',	name:'sfy_water_extractor',	img:'/fgfactory/sfy/water_extractor.png',	count:0,	reqs:{ 'coal_power':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'oil_extractor',	name:'sfy_oil_extractor',	img:'/fgfactory/sfy/oil_extractor.png',	count:0,	reqs:{ 'oil_processing':1 },	},
	{	type:'building',	group:'sfy_extractor',	id:'gas_extractor',	name:'sfy_gas_extractor',	img:'/fgfactory/sfy/gas_extractor.png',	count:0,	reqs:{ 'advanced_aluminum_production':1 },	},
	
	{	type:'building',	group:'sfy_machine',	id:'smelter',	name:'sfy_smelter',	img:'/fgfactory/sfy/smelter.png',	count:0,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'builder',	name:'sfy_builder',	img:'/fgfactory/sfy/builder.png',	count:0,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'assembler',	name:'sfy_assembler',	img:'/fgfactory/sfy/assembler.png',	count:0,	reqs:{ 'part_asssembly':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'foundry',	name:'sfy_foundry',	img:'/fgfactory/sfy/foundry.png',	count:0,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'refinery',	name:'sfy_refinery',	img:'/fgfactory/sfy/refinery.png',	count:0,	reqs:{ 'oil_processing':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'manufacturer',	name:'sfy_manufacturer',	img:'/fgfactory/sfy/manufacturer.png',	count:0,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'blender',	name:'sfy_blender',	img:'/fgfactory/sfy/blender.png',	count:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'particle_accelerator',	name:'sfy_particle_accelerator',	img:'/fgfactory/sfy/particle_accelerator.png',	count:0,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'converter',	name:'sfy_converter',	img:'/fgfactory/sfy/converter.png',	count:0,	reqs:{ 'matter_conversion':1 },	},
	{	type:'building',	group:'sfy_machine',	id:'quantum_encoder',	name:'sfy_quantum_encoder',	img:'/fgfactory/sfy/quantum_encoder.png',	count:0,	reqs:{ 'quantum_encoding':1 },	},
	
	// ITEMS
	
	{	type:'item',	group:'sfy_raw',	id:'iron_ore',	name:'sfy_iron_ore',	img:'/fgfactory/sfy/iron_ore.png',	count:0,	max:100,	prod:0,	},
	{	type:'item',	group:'sfy_raw',	id:'copper_ore',	name:'sfy_copper_ore',	img:'/fgfactory/sfy/copper_ore.png',	count:0,	max:100,	prod:0,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'limestone',	name:'sfy_limestone',	img:'/fgfactory/sfy/limestone.png',	count:0,	max:100,	prod:0,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'biomass',	name:'sfy_biomass',	img:'/fgfactory/sfy/biomass.png',	count:0,	max:200,	prod:0,	reqs:{ 'hub_upgrade_6':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'coal',	name:'sfy_coal',	img:'/fgfactory/sfy/coal.png',	count:0,	max:100,	prod:0,	reqs:{ 'coal_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'water',	name:'sfy_water',	img:'/fgfactory/sfy/water.png',	count:0,	max:400,	prod:0,	reqs:{ 'coal_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'crude_oil',	name:'sfy_crude_oil',	img:'/fgfactory/sfy/crude_oil.png',	count:0,	max:400,	prod:0,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'caterium_ore',	name:'sfy_caterium_ore',	img:'/fgfactory/sfy/caterium_ore.png',	count:0,	max:100,	prod:0,	reqs:{ 'petroleum_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'bauxite',	name:'sfy_bauxite',	img:'/fgfactory/sfy/bauxite.png',	count:0,	max:100,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'raw_quartz',	name:'sfy_raw_quartz',	img:'/fgfactory/sfy/raw_quartz.png',	count:0,	max:100,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'sulfur',	name:'sfy_sulfur',	img:'/fgfactory/sfy/sulfur.png',	count:0,	max:100,	prod:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'uranium',	name:'sfy_uranium',	img:'/fgfactory/sfy/uranium.png',	count:0,	max:100,	prod:0,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'nitrogen_gas',	name:'sfy_nitrogen_gas',	img:'/fgfactory/sfy/nitrogen_gas.png',	count:0,	max:400,	prod:0,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_raw',	id:'sam',	name:'sfy_sam',	img:'/fgfactory/sfy/sam.png',	count:0,	max:100,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	
	{	type:'item',	group:'sfy_material',	id:'iron_ingot',	name:'sfy_iron_ingot',	img:'/fgfactory/sfy/iron_ingot.png',	count:0,	max:100,	prod:0,	},
	{	type:'item',	group:'sfy_material',	id:'copper_ingot',	name:'sfy_copper_ingot',	img:'/fgfactory/sfy/copper_ingot.png',	count:0,	max:100,	prod:0,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_material',	id:'concrete',	name:'sfy_concrete',	img:'/fgfactory/sfy/concrete.png',	count:0,	max:500,	prod:0,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_material',	id:'steel_ingot',	name:'sfy_steel_ingot',	img:'/fgfactory/sfy/steel_ingot.png',	count:0,	max:100,	prod:0,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_material',	id:'plastic',	name:'sfy_plastic',	img:'/fgfactory/sfy/plastic.png',	count:0,	max:200,	prod:0,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_material',	id:'rubber',	name:'sfy_rubber',	img:'/fgfactory/sfy/rubber.png',	count:0,	max:200,	prod:0,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_material',	id:'fuel',	name:'sfy_fuel',	img:'/fgfactory/sfy/fuel.png',	count:0,	max:400,	prod:0,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_material',	id:'caterium_ingot',	name:'sfy_caterium_ingot',	img:'/fgfactory/sfy/caterium_ingot.png',	count:0,	max:100,	prod:0,	reqs:{ 'petroleum_power':1 },	},
	{	type:'item',	group:'sfy_material',	id:'aluminum_ingot',	name:'sfy_aluminum_ingot',	img:'/fgfactory/sfy/aluminum_ingot.png',	count:0,	max:100,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_material',	id:'quartz_crystal',	name:'sfy_quartz_crystal',	img:'/fgfactory/sfy/quartz_crystal.png',	count:0,	max:200,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_material',	id:'silica',	name:'sfy_silica',	img:'/fgfactory/sfy/silica.png',	count:0,	max:200,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_material',	id:'ficsite_ingot',	name:'sfy_ficsite_ingot',	img:'/fgfactory/sfy/ficsite_ingot.png',	count:0,	max:100,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_material',	id:'diamonds',	name:'sfy_diamonds',	img:'/fgfactory/sfy/diamonds.png',	count:0,	max:200,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	
	{	type:'item',	group:'sfy_component',	id:'iron_rod',	name:'sfy_iron_rod',	img:'/fgfactory/sfy/iron_rod.png',	count:0,	max:200,	prod:0,	},
	{	type:'item',	group:'sfy_component',	id:'iron_plate',	name:'sfy_iron_plate',	img:'/fgfactory/sfy/iron_plate.png',	count:0,	max:200,	prod:0,	reqs:{ 'hub_upgrade_1':1 },	},
	{	type:'item',	group:'sfy_component',	id:'wire',	name:'sfy_wire',	img:'/fgfactory/sfy/wire.png',	count:0,	max:500,	prod:0,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_component',	id:'cable',	name:'sfy_cable',	img:'/fgfactory/sfy/cable.png',	count:0,	max:200,	prod:0,	reqs:{ 'hub_upgrade_2':1 },	},
	{	type:'item',	group:'sfy_component',	id:'screw',	name:'sfy_screw',	img:'/fgfactory/sfy/screw.png',	count:0,	max:500,	prod:0,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_component',	id:'reinforced_iron_plate',	name:'sfy_reinforced_iron_plate',	img:'/fgfactory/sfy/reinforced_iron_plate.png',	count:0,	max:100,	prod:0,	reqs:{ 'hub_upgrade_3':1 },	},
	{	type:'item',	group:'sfy_component',	id:'copper_sheet',	name:'sfy_copper_sheet',	img:'/fgfactory/sfy/copper_sheet.png',	count:0,	max:200,	prod:0,	reqs:{ 'part_asssembly':1 },	},
	{	type:'item',	group:'sfy_component',	id:'rotor',	name:'sfy_rotor',	img:'/fgfactory/sfy/rotor.png',	count:0,	max:100,	prod:0,	reqs:{ 'part_asssembly':1 },	},
	{	type:'item',	group:'sfy_component',	id:'modular_frame',	name:'sfy_modular_frame',	img:'/fgfactory/sfy/modular_frame.png',	count:0,	max:50,	prod:0,	reqs:{ 'part_asssembly':1 },	},
	{	type:'item',	group:'sfy_component',	id:'steel_beam',	name:'sfy_steel_beam',	img:'/fgfactory/sfy/steel_beam.png',	count:0,	max:200,	prod:0,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'steel_pipe',	name:'sfy_steel_pipe',	img:'/fgfactory/sfy/steel_pipe.png',	count:0,	max:200,	prod:0,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'encased_industrial_beam',	name:'sfy_encased_industrial_beam',	img:'/fgfactory/sfy/encased_industrial_beam.png',	count:0,	max:100,	prod:0,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'stator',	name:'sfy_stator',	img:'/fgfactory/sfy/stator.png',	count:0,	max:100,	prod:0,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'motor',	name:'sfy_motor',	img:'/fgfactory/sfy/motor.png',	count:0,	max:50,	prod:0,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'circuit_board',	name:'sfy_circuit_board',	img:'/fgfactory/sfy/circuit_board.png',	count:0,	max:200,	prod:0,	reqs:{ 'oil_processing':1 },	},
	{	type:'item',	group:'sfy_component',	id:'quickwire',	name:'sfy_quickwire',	img:'/fgfactory/sfy/quickwire.png',	count:0,	max:500,	prod:0,	reqs:{ 'petroleum_power':1 },	},
	{	type:'item',	group:'sfy_component',	id:'computer',	name:'sfy_computer',	img:'/fgfactory/sfy/computer.png',	count:0,	max:50,	prod:0,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'item',	group:'sfy_component',	id:'heavy_modular_frame',	name:'sfy_heavy_modular_frame',	img:'/fgfactory/sfy/heavy_modular_frame.png',	count:0,	max:50,	prod:0,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'item',	group:'sfy_component',	id:'alumina_solution',	name:'sfy_alumina_solution',	img:'/fgfactory/sfy/alumina_solution.png',	count:0,	max:400,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component',	id:'aluminum_scrap',	name:'sfy_aluminum_scrap',	img:'/fgfactory/sfy/aluminum_scrap.png',	count:0,	max:500,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component',	id:'alclad_aluminum_sheet',	name:'sfy_alclad_aluminum_sheet',	img:'/fgfactory/sfy/alclad_aluminum_sheet.png',	count:0,	max:200,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component',	id:'aluminum_casing',	name:'sfy_aluminum_casing',	img:'/fgfactory/sfy/aluminum_casing.png',	count:0,	max:200,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component',	id:'radio_control_unit',	name:'sfy_radio_control_unit',	img:'/fgfactory/sfy/radio_control_unit.png',	count:0,	max:50,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component',	id:'crystal_oscillator',	name:'sfy_crystal_oscillator',	img:'/fgfactory/sfy/crystal_oscillator.png',	count:0,	max:100,	prod:0,	reqs:{ 'bauxite_refinement':1 },	},
	{	type:'item',	group:'sfy_component',	id:'ai_limiter',	name:'sfy_ai_limiter',	img:'/fgfactory/sfy/ai_limiter.png',	count:0,	max:100,	prod:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component',	id:'sulfuric_acid',	name:'sfy_sulfuric_acid',	img:'/fgfactory/sfy/sulfuric_acid.png',	count:0,	max:400,	prod:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component',	id:'high_speed_connector',	name:'sfy_high_speed_connector',	img:'/fgfactory/sfy/high_speed_connector.png',	count:0,	max:100,	prod:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component',	id:'battery',	name:'sfy_battery',	img:'/fgfactory/sfy/battery.png',	count:0,	max:200,	prod:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component',	id:'supercomputer',	name:'sfy_supercomputer',	img:'/fgfactory/sfy/supercomputer.png',	count:0,	max:50,	prod:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_component',	id:'encased_uranium_cell',	name:'sfy_encased_uranium_cell',	img:'/fgfactory/sfy/encased_uranium_cell.png',	count:0,	max:200,	prod:0,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_component',	id:'electromagnetic_control_rod',	name:'sfy_electromagnetic_control_rod',	img:'/fgfactory/sfy/electromagnetic_control_rod.png',	count:0,	max:100,	prod:0,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_component',	id:'uranium_fuel_rod',	name:'sfy_uranium_fuel_rod',	img:'/fgfactory/sfy/uranium_fuel_rod.png',	count:0,	max:50,	prod:0,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_component',	id:'heat_sink',	name:'sfy_heat_sink',	img:'/fgfactory/sfy/heat_sink.png',	count:0,	max:100,	prod:0,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'cooling_system',	name:'sfy_cooling_system',	img:'/fgfactory/sfy/cooling_system.png',	count:0,	max:100,	prod:0,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'fused_modular_frame',	name:'sfy_fused_modular_frame',	img:'/fgfactory/sfy/fused_modular_frame.png',	count:0,	max:50,	prod:0,	reqs:{ 'advanced_aluminum_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'turbo_motor',	name:'sfy_turbo_motor',	img:'/fgfactory/sfy/turbo_motor.png',	count:0,	max:50,	prod:0,	reqs:{ 'leading_edge_production':1 },	},
	{	type:'item',	group:'sfy_component',	id:'copper_powder',	name:'sfy_copper_powder',	img:'/fgfactory/sfy/copper_powder.png',	count:0,	max:500,	prod:0,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'item',	group:'sfy_component',	id:'pressure_conversion_cube',	name:'sfy_pressure_conversion_cube',	img:'/fgfactory/sfy/pressure_conversion_cube.png',	count:0,	max:50,	prod:0,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'item',	group:'sfy_component',	id:'time_crystal',	name:'sfy_time_crystal',	img:'/fgfactory/sfy/time_crystal.png',	count:0,	max:200,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component',	id:'ficsite_trigon',	name:'sfy_ficsite_trigon',	img:'/fgfactory/sfy/ficsite_trigon.png',	count:0,	max:200,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component',	id:'reanimated_sam',	name:'sfy_reanimated_sam',	img:'/fgfactory/sfy/reanimated_sam.png',	count:0,	max:100,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component',	id:'sam_fluctuator',	name:'sfy_sam_fluctuator',	img:'/fgfactory/sfy/sam_fluctuator.png',	count:0,	max:100,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_component',	id:'dark_matter_residue',	name:'sfy_dark_matter_residue',	img:'/fgfactory/sfy/dark_matter_residue.png',	count:0,	max:400,	prod:0,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_component',	id:'excited_photonic_matter',	name:'sfy_excited_photonic_matter',	img:'/fgfactory/sfy/excited_photonic_matter.png',	count:0,	max:400,	prod:0,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_component',	id:'dark_matter_crystal',	name:'sfy_dark_matter_crystal',	img:'/fgfactory/sfy/dark_matter_crystal.png',	count:0,	max:200,	prod:0,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_component',	id:'superposition_oscillator',	name:'sfy_superposition_oscillator',	img:'/fgfactory/sfy/superposition_oscillator.png',	count:0,	max:100,	prod:0,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_component',	id:'neural_quantum_processor',	name:'sfy_neural_quantum_processor',	img:'/fgfactory/sfy/neural_quantum_processor.png',	count:0,	max:100,	prod:0,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_component',	id:'singularity_cell',	name:'sfy_singularity_cell',	img:'/fgfactory/sfy/singularity_cell.png',	count:0,	max:50,	prod:0,	reqs:{ 'spatial_energy_regulation':1 },	},
	
	{	type:'item',	group:'sfy_part',	id:'smart_plating',	name:'sfy_smart_plating',	img:'/fgfactory/sfy/smart_plating.png',	count:0,	max:50,	prod:0,	reqs:{ 'part_asssembly':1 },	},
	{	type:'item',	group:'sfy_part',	id:'versatile_framework',	name:'sfy_versatile_framework',	img:'/fgfactory/sfy/versatile_framework.png',	count:0,	max:50,	prod:0,	reqs:{ 'basic_steel_production':1 },	},
	{	type:'item',	group:'sfy_part',	id:'automated_wiring',	name:'sfy_automated_wiring',	img:'/fgfactory/sfy/automated_wiring.png',	count:0,	max:50,	prod:0,	reqs:{ 'advanced_steel_production':1 },	},
	{	type:'item',	group:'sfy_part',	id:'modular_engine',	name:'sfy_modular_engine',	img:'/fgfactory/sfy/modular_engine.png',	count:0,	max:50,	prod:0,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'item',	group:'sfy_part',	id:'adaptive_control_unit',	name:'sfy_adaptive_control_unit',	img:'/fgfactory/sfy/adaptive_control_unit.png',	count:0,	max:50,	prod:0,	reqs:{ 'industrial_manufacturing':1 },	},
	{	type:'item',	group:'sfy_part',	id:'assembly_director_system',	name:'sfy_assembly_director_system',	img:'/fgfactory/sfy/assembly_director_system.png',	count:0,	max:50,	prod:0,	reqs:{ 'control_system_development':1 },	},
	{	type:'item',	group:'sfy_part',	id:'magnetic_field_generator',	name:'sfy_magnetic_field_generator',	img:'/fgfactory/sfy/magnetic_field_generator.png',	count:0,	max:50,	prod:0,	reqs:{ 'nuclear_power':1 },	},
	{	type:'item',	group:'sfy_part',	id:'thermal_propulsion_rocket',	name:'sfy_thermal_propulsion_rocket',	img:'/fgfactory/sfy/thermal_propulsion_rocket.png',	count:0,	max:50,	prod:0,	reqs:{ 'leading_edge_production':1 },	},
	{	type:'item',	group:'sfy_part',	id:'nuclear_pasta',	name:'sfy_nuclear_pasta',	img:'/fgfactory/sfy/nuclear_pasta.png',	count:0,	max:50,	prod:0,	reqs:{ 'particle_enrichment':1 },	},
	{	type:'item',	group:'sfy_part',	id:'biochemical_sculptor',	name:'sfy_biochemical_sculptor',	img:'/fgfactory/sfy/biochemical_sculptor.png',	count:0,	max:50,	prod:0,	reqs:{ 'matter_conversion':1 },	},
	{	type:'item',	group:'sfy_part',	id:'ai_expansion_server',	name:'sfy_ai_expansion_server',	img:'/fgfactory/sfy/ai_expansion_server.png',	count:0,	max:50,	prod:0,	reqs:{ 'quantum_encoding':1 },	},
	{	type:'item',	group:'sfy_part',	id:'ballistic_warp_drive',	name:'sfy_ballistic_warp_drive',	img:'/fgfactory/sfy/ballistic_warp_drive.png',	count:0,	max:50,	prod:0,	reqs:{ 'spatial_energy_regulation':1 },	},
	
	// MANUALS
	
	{	type:'manual',	id:'manual_hub_upgrade_1',	results:{ 'hub_upgrade_1':1 },	costs:{ 'iron_rod':10 },	},
	{	type:'manual',	id:'manual_hub_upgrade_2',	results:{ 'hub_upgrade_2':1, 'energy':20e6 },	costs:{ 'iron_rod':20, 'iron_plate':10 },	},
	{	type:'manual',	id:'manual_hub_upgrade_3',	results:{ 'hub_upgrade_3':1 },	costs:{ 'iron_rod':20, 'iron_plate':20, 'wire':20 },	},
	{	type:'manual',	id:'manual_hub_upgrade_5',	results:{ 'hub_upgrade_5':1, 'energy':20e6 },	costs:{ 'iron_rod':75, 'cable':50, 'concrete':20 },	},
	{	type:'manual',	id:'manual_hub_upgrade_6',	results:{ 'hub_upgrade_6':1 },	costs:{ 'iron_rod':100, 'iron_plate':100, 'wire':100, 'concrete':50 },	},
	
	{	type:'manual',	id:'manual_part_asssembly',	results:{ 'part_asssembly':1 },	costs:{ 'cable':200, 'iron_rod':200, 'screw':500, 'iron_plate':300 },	},
	{	type:'manual',	id:'manual_coal_power',	results:{ 'coal_power':1 },	costs:{ 'reinforced_iron_plate':150, 'rotor':50, 'cable':500 },	},
	{	type:'manual',	id:'manual_basic_steel_production',	results:{ 'basic_steel_production':1 },	costs:{ 'modular_frame':50, 'rotor':150, 'concrete':500, 'wire':1000 },	},
	{	type:'manual',	id:'manual_logistics',	results:{ 'logistics':1 },	costs:{ 'steel_beam':200, 'steel_pipe':200, 'reinforced_iron_plate':400 },	},
	{	type:'manual',	id:'manual_advanced_steel_production',	results:{ 'advanced_steel_production':1 },	costs:{ 'steel_pipe':100, 'modular_frame':100, 'rotor':200, 'concrete':500 },	},
	{	type:'manual',	id:'manual_oil_processing',	results:{ 'oil_processing':1 },	costs:{ 'motor':50, 'encased_industrial_beam':100, 'steel_pipe':500, 'copper_sheet':500 },	},
	{	type:'manual',	id:'manual_petroleum_power',	results:{ 'petroleum_power':1 },	costs:{ 'motor':100, 'encased_industrial_beam':100, 'rubber':200, 'plastic':200 },	},
	{	type:'manual',	id:'manual_industrial_manufacturing',	results:{ 'industrial_manufacturing':1 },	costs:{ 'motor':200, 'modular_frame':200, 'plastic':400, 'cable':1000 },	},
	{	type:'manual',	id:'manual_bauxite_refinement',	results:{ 'bauxite_refinement':1 },	costs:{ 'computer':100, 'heavy_modular_frame':100, 'motor':200, 'rubber':500 },	},
	{	type:'manual',	id:'manual_control_system_development',	results:{ 'control_system_development':1 },	costs:{ 'alclad_aluminum_sheet':200, 'aluminum_casing':400, 'computer':200, 'plastic':1000 },	},
	{	type:'manual',	id:'manual_nuclear_power',	results:{ 'nuclear_power':1 },	costs:{ 'supercomputer':50, 'heavy_modular_frame':200, 'cable':1000, 'concrete':2000 },	},
	{	type:'manual',	id:'manual_advanced_aluminum_production',	results:{ 'advanced_aluminum_production':1 },	costs:{ 'radio_control_unit':50, 'aluminum_casing':200, 'alclad_aluminum_sheet':400, 'wire':3000 },	},
	{	type:'manual',	id:'manual_leading_edge_production',	results:{ 'leading_edge_production':1 },	costs:{ 'fused_modular_frame':50, 'supercomputer':100, 'steel_pipe':1000 },	},
	{	type:'manual',	id:'manual_particle_enrichment',	results:{ 'particle_enrichment':1 },	costs:{ 'turbo_motor':50, 'fused_modular_frame':100, 'cooling_system':200, 'quickwire':2500 },	},
	{	type:'manual',	id:'manual_matter_conversion',	results:{ 'matter_conversion':1 },	costs:{ 'fused_modular_frame':100, 'radio_control_unit':250, 'cooling_system':500, },	},
	{	type:'manual',	id:'manual_quantum_encoding',	results:{ 'quantum_encoding':1 },	costs:{ 'time_crystal':50, 'ficsite_trigon':100, 'turbo_motor':200, 'supercomputer':400 },	},
	{	type:'manual',	id:'manual_spatial_energy_regulation',	results:{ 'spatial_energy_regulation':1 },	costs:{ 'superposition_oscillator':100, 'turbo_motor':250, 'radio_control_unit':500, 'sam_fluctuator':1000 },	},
	
	{	type:'manual',	id:'manual_phase_0',	results:{ 'phase_0':1 },	costs:{ 'concrete':500, 'iron_plate':250, 'iron_rod':400, 'wire':1500 },	},
	{	type:'manual',	id:'manual_phase_1',	results:{ 'phase_1':1 },	costs:{ 'smart_plating':50 },	},
	{	type:'manual',	id:'manual_phase_2',	results:{ 'phase_2':1 },	costs:{ 'smart_plating':1000, 'versatile_framework':1000, 'automated_wiring':100 },	},
	{	type:'manual',	id:'manual_phase_3',	results:{ 'phase_3':1 },	costs:{ 'versatile_framework':2500, 'modular_engine':500, 'adaptive_control_unit':100 },	},
	{	type:'manual',	id:'manual_phase_4',	results:{ 'phase_4':1 },	costs:{ 'assembly_director_system':500, 'magnetic_field_generator':500, 'nuclear_pasta':100, 'thermal_propulsion_rocket':250 },	},
	{	type:'manual',	id:'manual_phase_5',	results:{ 'phase_5':1 },	costs:{ 'nuclear_pasta':1000, 'biochemical_sculptor':1000, 'ai_expansion_server':256, 'ballistic_warp_drive':200 },	},

	{	type:'manual',	id:'manual_storage_container_1',	results:{ 'storage_container_1':1 },	costs:{ 'iron_plate':10, 'iron_rod':10 },	},
	{	type:'manual',	id:'manual_storage_container_2',	results:{ 'storage_container_2':1 },	costs:{ 'steel_beam':20, 'steel_pipe':20 },	},
	{	type:'manual',	id:'manual_fluid_buffer_1',	results:{ 'fluid_buffer_1':1 },	costs:{ 'copper_sheet':10, 'modular_frame':5 },	},
	{	type:'manual',	id:'manual_fluid_buffer_2',	results:{ 'fluid_buffer_2':1 },	costs:{ 'encased_industrial_beam':5, 'copper_sheet':10, 'plastic':25 },	},
	
	{	type:'manual',	id:'manual_biomass_burner',	results:{ 'biomass_burner':1, 'energy':30e6 },	costs:{ 'iron_plate':15, 'iron_rod':15, 'wire':25 },	inputs:{ 'biomass':0.15 },	},
	{	type:'manual',	id:'manual_coal_generator',	results:{ 'coal_generator':1, 'energy':75e6 },	costs:{ 'reinforced_iron_plate':20, 'rotor':10, 'cable':30 },	inputs:{ 'coal':0.25, 'water':0.75 },	},
	{	type:'manual',	id:'manual_fuel_generator',	results:{ 'fuel_generator':1, 'energy':250e6 },	costs:{ 'motor':15, 'encased_industrial_beam':15, 'copper_sheet':30, 'rubber':50, 'quickwire':50 },	inputs:{ 'fuel':0.5 },	},
	{	type:'manual',	id:'manual_nuclear_power_plant',	results:{ 'nuclear_power_plant':1, 'energy':2500e6 },	costs:{ 'supercomputer':10, 'heavy_modular_frame':25, 'alclad_aluminum_sheet':100, 'cable':200, 'concrete':250 },	inputs:{ 'uranium_fuel_rod':0.01, 'water':4 },	},
	
	{	type:'manual',	id:'manual_miner_0',	results:{ 'miner_0':1 },	costs:{ 'iron_plate':2, 'iron_rod':4 },	},
	{	type:'manual',	id:'manual_miner_1',	results:{ 'miner_1':1 },	costs:{ 'iron_plate':10, 'concrete':10 },	upgrades:{ 'miner_0':1 },	},
	{	type:'manual',	id:'manual_miner_2',	results:{ 'miner_2':1 },	costs:{ 'encased_industrial_beam':10, 'steel_pipe':20, 'modular_frame':10 },	upgrades:{ 'miner_0':2 },	},
	{	type:'manual',	id:'manual_miner_3',	results:{ 'miner_3':1 },	costs:{ 'steel_pipe':50, 'supercomputer':5, 'fused_modular_frame':10, 'turbo_motor':3 },	upgrades:{ 'miner_0':3 },	},
	{	type:'manual',	id:'manual_water_extractor',	results:{ 'water_extractor':1 },	costs:{ 'copper_sheet':20, 'reinforced_iron_plate':10, 'rotor':10 },	},
	{	type:'manual',	id:'manual_oil_extractor',	results:{ 'oil_extractor':1 },	costs:{ 'motor':15, 'encased_industrial_beam':20, 'cable':60 },	},
	{	type:'manual',	id:'manual_gas_extractor',	results:{ 'gas_extractor':1 },	costs:{ 'radio_control_unit':10, 'heavy_modular_frame':25, 'motor':50, 'alclad_aluminum_sheet':50, 'rubber':100, 'steel_beam':10, 'aluminum_casing':10 },	},
	
	{	type:'manual',	id:'manual_smelter',	results:{ 'smelter':1 },	costs:{ 'iron_rod':5, 'wire':8 },	},
	{	type:'manual',	id:'manual_builder',	results:{ 'builder':1 },	costs:{ 'reinforced_iron_plate':2, 'cable':8 },	},
	{	type:'manual',	id:'manual_assembler',	results:{ 'assembler':1 },	costs:{ 'reinforced_iron_plate':2, 'rotor':4, 'cable':10 },	},
	{	type:'manual',	id:'manual_foundry',	results:{ 'foundry':1 },	costs:{ 'modular_frame':10, 'rotor':10, 'concrete':20 },	},
	{	type:'manual',	id:'manual_refinery',	results:{ 'refinery':1 },	costs:{ 'motor':10, 'encased_industrial_beam':10, 'steel_pipe':30, 'copper_sheet':20 },	},
	{	type:'manual',	id:'manual_manufacturer',	results:{ 'manufacturer':1 },	costs:{ 'motor':10, 'modular_frame':20, 'plastic':50, 'cable':50 },	},
	{	type:'manual',	id:'manual_blender',	results:{ 'blender':1 },	costs:{ 'computer':10, 'heavy_modular_frame':10, 'motor':20, 'aluminum_casing':50 },	},
	{	type:'manual',	id:'manual_particle_accelerator',	results:{ 'particle_accelerator':1 },	costs:{ 'turbo_motor':10, 'supercomputer':10, 'fused_modular_frame':25, 'cooling_system':50, 'quickwire':500 },	},
	{	type:'manual',	id:'manual_converter',	results:{ 'converter':1 },	costs:{ 'fused_modular_frame':10, 'cooling_system':25, 'radio_control_unit':50, 'sam_fluctuator':100 },	},
	{	type:'manual',	id:'manual_quantum_encoder',	results:{ 'quantum_encoder':1 },	costs:{ 'turbo_motor':20, 'supercomputer':20, 'cooling_system':50, 'time_crystal':50, 'ficsite_trigon':100 },	},

	{	type:'manual',	id:'manual_iron_ore',	results:{ 'iron_ore':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_copper_ore',	results:{ 'copper_ore':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_limestone',	results:{ 'limestone':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_coal',	results:{ 'coal':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_caterium_ore',	results:{ 'caterium_ore':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_bauxite',	results:{ 'bauxite':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_raw_quartz',	results:{ 'raw_quartz':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_sulfur',	results:{ 'sulfur':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_uranium',	results:{ 'uranium':1 },	status:'waiting',	seconds:2,	},
	{	type:'manual',	id:'manual_sam',	results:{ 'sam':1 },	status:'waiting',	seconds:2,	},

	{	type:'manual',	id:'manual_iron_ingot',	results:{ 'iron_ingot':1 },	status:'waiting',	seconds:0.75,	costs:{ 'iron_ore':1 },	},
	{	type:'manual',	id:'manual_copper_ingot',	results:{ 'copper_ingot':1 },	status:'waiting',	seconds:0.75,	costs:{ 'copper_ore':1 },	},
	{	type:'manual',	id:'manual_concrete',	results:{ 'concrete':1 },	status:'waiting',	seconds:0.5,	costs:{ 'limestone':3 },	},
	{	type:'manual',	id:'manual_ai_limiter',	results:{ 'ai_limiter':1 },	status:'waiting',	seconds:0.25*6,	costs:{ 'copper_sheet':5, 'quickwire':20 },	},
	{	type:'manual',	id:'manual_alclad_aluminum_sheet',	results:{ 'alclad_aluminum_sheet':3 },	status:'waiting',	seconds:0.25*6,	costs:{ 'aluminum_ingot':3, 'copper_ingot':1 },	},
	{	type:'manual',	id:'manual_aluminum_casing',	results:{ 'aluminum_casing':2 },	status:'waiting',	seconds:0.25*2,	costs:{ 'aluminum_ingot':3 },	},
	{	type:'manual',	id:'manual_aluminum_ingot',	results:{ 'aluminum_ingot':4 },	status:'waiting',	seconds:0.25*6,	costs:{ 'aluminum_scrap':6, 'silica':5 },	},
	{	type:'manual',	id:'manual_cable',	results:{ 'cable':1 },	status:'waiting',	seconds:0.25*1,	costs:{ 'wire':2 },	},
	{	type:'manual',	id:'manual_caterium_ingot',	results:{ 'caterium_ingot':1 },	status:'waiting',	seconds:0.25*4,	costs:{ 'caterium_ore':3 },	},
	{	type:'manual',	id:'manual_circuit_board',	results:{ 'circuit_board':1 },	status:'waiting',	seconds:0.25*6,	costs:{ 'copper_sheet':2, 'plastic':4 },	},
	{	type:'manual',	id:'manual_computer',	results:{ 'computer':1 },	status:'waiting',	seconds:0.25*18,	costs:{ 'circuit_board':4, 'cable':8, 'plastic':16 },	},
	{	type:'manual',	id:'manual_copper_powder',	results:{ 'copper_powder':5 },	status:'waiting',	seconds:0.25*3,	costs:{ 'copper_ingot':30 },	},
	{	type:'manual',	id:'manual_copper_sheet',	results:{ 'copper_sheet':1 },	status:'waiting',	seconds:0.25*3,	costs:{ 'copper_ingot':2 },	},
	{	type:'manual',	id:'manual_crystal_oscillator',	results:{ 'crystal_oscillator':2 },	status:'waiting',	seconds:0.25*18,	costs:{ 'quartz_crystal':36, 'cable':28, 'reinforced_iron_plate':5 },	},
	{	type:'manual',	id:'manual_electromagnetic_control_rod',	results:{ 'electromagnetic_control_rod':2 },	status:'waiting',	seconds:0.25*15,	costs:{ 'stator':3, 'ai_limiter':2 },	},
	{	type:'manual',	id:'manual_encased_industrial_beam',	results:{ 'encased_industrial_beam':1 },	status:'waiting',	seconds:0.25*5,	costs:{ 'steel_beam':3, 'concrete':6 },	},
	{	type:'manual',	id:'manual_ficsite_trigon',	results:{ 'ficsite_trigon':3 },	status:'waiting',	seconds:0.25*3,	costs:{ 'ficsite_ingot':1 },	},
	{	type:'manual',	id:'manual_heat_sink',	results:{ 'heat_sink':1 },	status:'waiting',	seconds:0.25*6,	costs:{ 'alclad_aluminum_sheet':5, 'copper_sheet':3 },	},
	{	type:'manual',	id:'manual_heavy_modular_frame',	results:{ 'heavy_modular_frame':1 },	status:'waiting',	seconds:0.25*9,	costs:{ 'modular_frame':5, 'steel_pipe':20, 'encased_industrial_beam':5 },	},
	{	type:'manual',	id:'manual_high_speed_connector',	results:{ 'high_speed_connector':1 },	status:'waiting',	seconds:0.25*8,	costs:{ 'quickwire':56, 'cable':10, 'circuit_board':1 },	},
	{	type:'manual',	id:'manual_iron_plate',	results:{ 'iron_plate':2 },	status:'waiting',	seconds:0.25*3,	costs:{ 'iron_ingot':3 },	},
	{	type:'manual',	id:'manual_iron_rod',	results:{ 'iron_rod':1 },	status:'waiting',	seconds:0.25*1,	costs:{ 'iron_ingot':1 },	},
	{	type:'manual',	id:'manual_modular_frame',	results:{ 'modular_frame':2 },	status:'waiting',	seconds:0.25*15,	costs:{ 'reinforced_iron_plate':3, 'iron_rod':12 },	},
	{	type:'manual',	id:'manual_motor',	results:{ 'motor':1 },	status:'waiting',	seconds:0.25*12,	costs:{ 'rotor':2, 'stator':2 },	},
	{	type:'manual',	id:'manual_pressure_conversion_cube',	results:{ 'pressure_conversion_cube':1 },	status:'waiting',	seconds:0.25*60,	costs:{ 'fused_modular_frame':1, 'radio_control_unit':2 },	},
	{	type:'manual',	id:'manual_quartz_crystal',	results:{ 'quartz_crystal':3 },	status:'waiting',	seconds:0.25*8,	costs:{ 'raw_quartz':5 },	},
	{	type:'manual',	id:'manual_quickwire',	results:{ 'quickwire':5 },	status:'waiting',	seconds:0.25*5,	costs:{ 'caterium_ingot':1 },	},
	{	type:'manual',	id:'manual_radio_control_unit',	results:{ 'radio_control_unit':2 },	status:'waiting',	seconds:0.25*24,	costs:{ 'aluminum_casing':32, 'crystal_oscillator':1, 'computer':2 },	},
	{	type:'manual',	id:'manual_reanimated_sam',	results:{ 'reanimated_sam':1 },	status:'waiting',	seconds:0.25*1,	costs:{ 'sam':4 },	},
	{	type:'manual',	id:'manual_reinforced_iron_plate',	results:{ 'reinforced_iron_plate':1 },	status:'waiting',	seconds:0.25*6,	costs:{ 'iron_plate':6, 'screw':12 },	},
	{	type:'manual',	id:'manual_rotor',	results:{ 'rotor':1 },	status:'waiting',	seconds:0.25*6,	costs:{ 'iron_rod':5, 'screw':25 },	},
	{	type:'manual',	id:'manual_sam_fluctuator',	results:{ 'sam_fluctuator':1 },	status:'waiting',	seconds:0.25*3,	costs:{ 'reanimated_sam':6, 'wire':5, 'steel_pipe':3 },	},
	{	type:'manual',	id:'manual_screw',	results:{ 'screw':4 },	status:'waiting',	seconds:0.25*3,	costs:{ 'iron_rod':1 },	},
	{	type:'manual',	id:'manual_silica',	results:{ 'silica':5 },	status:'waiting',	seconds:0.25*8,	costs:{ 'raw_quartz':3 },	},
	{	type:'manual',	id:'manual_stator',	results:{ 'stator':1 },	status:'waiting',	seconds:0.25*9,	costs:{ 'steel_pipe':3, 'wire':8 },	},
	{	type:'manual',	id:'manual_steel_beam',	results:{ 'steel_beam':1 },	status:'waiting',	seconds:0.25*2,	costs:{ 'steel_ingot':4 },	},
	{	type:'manual',	id:'manual_steel_ingot',	results:{ 'steel_ingot':3 },	status:'waiting',	seconds:0.25*6,	costs:{ 'iron_ore':3, 'coal':3 },	},
	{	type:'manual',	id:'manual_steel_pipe',	results:{ 'steel_pipe':2 },	status:'waiting',	seconds:0.25*3,	costs:{ 'steel_ingot':3 },	},
	{	type:'manual',	id:'manual_supercomputer',	results:{ 'supercomputer':1 },	status:'waiting',	seconds:0.25*24,	costs:{ 'computer':4, 'ai_limiter':2, 'high_speed_connector':3, 'plastic':28 },	},
	{	type:'manual',	id:'manual_turbo_motor',	results:{ 'turbo_motor':1 },	status:'waiting',	seconds:0.25*32,	costs:{ 'cooling_system':4, 'radio_control_unit':2, 'motor':4 },	},
	{	type:'manual',	id:'manual_wire',	results:{ 'wire':2 },	status:'waiting',	seconds:0.25*2,	costs:{ 'copper_ingot':1 },	},
	
	// STORERS

	{	type:'storer',	id:'storer_iron_ore_1',	storages:{ 'iron_ore':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_copper_ore_1',	storages:{ 'copper_ore':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_limestone_1',	storages:{ 'limestone':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_biomass_1',	storages:{ 'biomass':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_coal_1',	storages:{ 'coal':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_caterium_ore_1',	storages:{ 'caterium_ore':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_bauxite_1',	storages:{ 'bauxite':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_raw_quartz_1',	storages:{ 'raw_quartz':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_sulfur_1',	storages:{ 'sulfur':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_uranium_1',	storages:{ 'uranium':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_sam_1',	storages:{ 'sam':100 },	assign:{ id:'storage_container_1', count:0 },	},

	{	type:'storer',	id:'storer_iron_ingot_1',	storages:{ 'iron_ingot':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_copper_ingot_1',	storages:{ 'copper_ingot':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_concrete_1',	storages:{ 'concrete':500 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_plastic_1',	storages:{ 'plastic':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_rubber_1',	storages:{ 'rubber':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_caterium_ingot_1',	storages:{ 'caterium_ingot':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_steel_ingot_1',	storages:{ 'steel_ingot':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_aluminum_ingot_1',	storages:{ 'aluminum_ingot':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_quartz_crystal_1',	storages:{ 'quartz_crystal':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_silica_1',	storages:{ 'silica':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_ficsite_ingot_1',	storages:{ 'ficsite_ingot':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_diamonds_1',	storages:{ 'diamonds':200 },	assign:{ id:'storage_container_1', count:0 },	},
						
	{	type:'storer',	id:'storer_iron_rod_1',	storages:{ 'iron_rod':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_iron_plate_1',	storages:{ 'iron_plate':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_wire_1',	storages:{ 'wire':500 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_cable_1',	storages:{ 'cable':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_screw_1',	storages:{ 'screw':500 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_reinforced_iron_plate_1',	storages:{ 'reinforced_iron_plate':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_copper_sheet_1',	storages:{ 'copper_sheet':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_rotor_1',	storages:{ 'rotor':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_modular_frame_1',	storages:{ 'modular_frame':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_steel_beam_1',	storages:{ 'steel_beam':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_steel_pipe_1',	storages:{ 'steel_pipe':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_encased_industrial_beam_1',	storages:{ 'encased_industrial_beam':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_stator_1',	storages:{ 'stator':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_motor_1',	storages:{ 'motor':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_circuit_board_1',	storages:{ 'circuit_board':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_quickwire_1',	storages:{ 'quickwire':500 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_computer_1',	storages:{ 'computer':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_heavy_modular_frame_1',	storages:{ 'heavy_modular_frame':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_aluminum_scrap_1',	storages:{ 'aluminum_scrap':500 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_alclad_aluminum_sheet_1',	storages:{ 'alclad_aluminum_sheet':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_aluminum_casing_1',	storages:{ 'aluminum_casing':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_ai_limiter_1',	storages:{ 'ai_limiter':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_crystal_oscillator_1',	storages:{ 'crystal_oscillator':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_radio_control_unit_1',	storages:{ 'radio_control_unit':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_high_speed_connector_1',	storages:{ 'high_speed_connector':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_battery_1',	storages:{ 'battery':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_supercomputer_1',	storages:{ 'supercomputer':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_encased_uranium_cell_1',	storages:{ 'encased_uranium_cell':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_electromagnetic_control_rod_1',	storages:{ 'electromagnetic_control_rod':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_uranium_fuel_rod_1',	storages:{ 'uranium_fuel_rod':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_heat_sink_1',	storages:{ 'heat_sink':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_cooling_system_1',	storages:{ 'cooling_system':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_fused_modular_frame_1',	storages:{ 'fused_modular_frame':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_turbo_motor_1',	storages:{ 'turbo_motor':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_copper_powder_1',	storages:{ 'copper_powder':500 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_pressure_conversion_cube_1',	storages:{ 'pressure_conversion_cube':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_time_crystal_1',	storages:{ 'time_crystal':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_ficsite_trigon_1',	storages:{ 'ficsite_trigon':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_reanimated_sam_1',	storages:{ 'reanimated_sam':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_sam_fluctuator_1',	storages:{ 'sam_fluctuator':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_dark_matter_crystal_1',	storages:{ 'dark_matter_crystal':200 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_superposition_oscillator_1',	storages:{ 'superposition_oscillator':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_neural_quantum_processor_1',	storages:{ 'neural_quantum_processor':100 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_singularity_cell_1',	storages:{ 'singularity_cell':50 },	assign:{ id:'storage_container_1', count:0 },	},
						
	{	type:'storer',	id:'storer_smart_plating_1',	storages:{ 'smart_plating':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_versatile_framework_1',	storages:{ 'versatile_framework':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_automated_wiring_1',	storages:{ 'automated_wiring':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_modular_engine_1',	storages:{ 'modular_engine':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_adaptive_control_unit_1',	storages:{ 'adaptive_control_unit':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_assembly_director_system_1',	storages:{ 'assembly_director_system':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_magnetic_field_generator_1',	storages:{ 'magnetic_field_generator':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_nuclear_pasta_1',	storages:{ 'nuclear_pasta':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_thermal_propulsion_rocket_1',	storages:{ 'thermal_propulsion_rocket':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_biochemical_sculptor_1',	storages:{ 'biochemical_sculptor':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_ai_expansion_server_1',	storages:{ 'ai_expansion_server':50 },	assign:{ id:'storage_container_1', count:0 },	},
	{	type:'storer',	id:'storer_ballistic_warp_drive_1',	storages:{ 'ballistic_warp_drive':50 },	assign:{ id:'storage_container_1', count:0 },	},
	
	{	type:'storer',	id:'storer_iron_ore_2',	storages:{ 'iron_ore':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_copper_ore_2',	storages:{ 'copper_ore':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_limestone_2',	storages:{ 'limestone':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_biomass_2',	storages:{ 'biomass':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_coal_2',	storages:{ 'coal':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_caterium_ore_2',	storages:{ 'caterium_ore':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_bauxite_2',	storages:{ 'bauxite':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_raw_quartz_2',	storages:{ 'raw_quartz':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_sulfur_2',	storages:{ 'sulfur':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_uranium_2',	storages:{ 'uranium':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_sam_2',	storages:{ 'sam':200 },	assign:{ id:'storage_container_2', count:0 },	},

	{	type:'storer',	id:'storer_iron_ingot_2',	storages:{ 'iron_ingot':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_copper_ingot_2',	storages:{ 'copper_ingot':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_concrete_2',	storages:{ 'concrete':1000 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_plastic_2',	storages:{ 'plastic':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_rubber_2',	storages:{ 'rubber':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_caterium_ingot_2',	storages:{ 'caterium_ingot':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_steel_ingot_2',	storages:{ 'steel_ingot':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_aluminum_ingot_2',	storages:{ 'aluminum_ingot':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_quartz_crystal_2',	storages:{ 'quartz_crystal':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_silica_2',	storages:{ 'silica':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_ficsite_ingot_2',	storages:{ 'ficsite_ingot':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_diamonds_2',	storages:{ 'diamonds':200 },	assign:{ id:'storage_container_2', count:0 },	},
						
	{	type:'storer',	id:'storer_iron_rod_2',	storages:{ 'iron_rod':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_iron_plate_2',	storages:{ 'iron_plate':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_wire_2',	storages:{ 'wire':1000 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_cable_2',	storages:{ 'cable':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_screw_2',	storages:{ 'screw':1000 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_reinforced_iron_plate_2',	storages:{ 'reinforced_iron_plate':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_copper_sheet_2',	storages:{ 'copper_sheet':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_rotor_2',	storages:{ 'rotor':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_modular_frame_2',	storages:{ 'modular_frame':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_steel_beam_2',	storages:{ 'steel_beam':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_steel_pipe_2',	storages:{ 'steel_pipe':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_encased_industrial_beam_2',	storages:{ 'encased_industrial_beam':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_stator_2',	storages:{ 'stator':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_motor_2',	storages:{ 'motor':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_circuit_board_2',	storages:{ 'circuit_board':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_quickwire_2',	storages:{ 'quickwire':1000 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_computer_2',	storages:{ 'computer':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_heavy_modular_frame_2',	storages:{ 'heavy_modular_frame':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_aluminum_scrap_2',	storages:{ 'aluminum_scrap':1000 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_alclad_aluminum_sheet_2',	storages:{ 'alclad_aluminum_sheet':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_aluminum_casing_2',	storages:{ 'aluminum_casing':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_ai_limiter_2',	storages:{ 'ai_limiter':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_crystal_oscillator_2',	storages:{ 'crystal_oscillator':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_radio_control_unit_2',	storages:{ 'radio_control_unit':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_high_speed_connector_2',	storages:{ 'high_speed_connector':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_battery_2',	storages:{ 'battery':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_supercomputer_2',	storages:{ 'supercomputer':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_encased_uranium_cell_2',	storages:{ 'encased_uranium_cell':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_electromagnetic_control_rod_2',	storages:{ 'electromagnetic_control_rod':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_uranium_fuel_rod_2',	storages:{ 'uranium_fuel_rod':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_heat_sink_2',	storages:{ 'heat_sink':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_cooling_system_2',	storages:{ 'cooling_system':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_fused_modular_frame_2',	storages:{ 'fused_modular_frame':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_turbo_motor_2',	storages:{ 'turbo_motor':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_copper_powder_2',	storages:{ 'copper_powder':1000 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_pressure_conversion_cube_2',	storages:{ 'pressure_conversion_cube':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_time_crystal_2',	storages:{ 'time_crystal':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_ficsite_trigon_2',	storages:{ 'ficsite_trigon':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_reanimated_sam_2',	storages:{ 'reanimated_sam':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_sam_fluctuator_2',	storages:{ 'sam_fluctuator':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_dark_matter_crystal_2',	storages:{ 'dark_matter_crystal':400 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_superposition_oscillator_2',	storages:{ 'superposition_oscillator':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_neural_quantum_processor_2',	storages:{ 'neural_quantum_processor':200 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_singularity_cell_2',	storages:{ 'singularity_cell':100 },	assign:{ id:'storage_container_2', count:0 },	},
						
	{	type:'storer',	id:'storer_smart_plating_2',	storages:{ 'smart_plating':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_versatile_framework_2',	storages:{ 'versatile_framework':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_automated_wiring_2',	storages:{ 'automated_wiring':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_modular_engine_2',	storages:{ 'modular_engine':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_adaptive_control_unit_2',	storages:{ 'adaptive_control_unit':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_assembly_director_system_2',	storages:{ 'assembly_director_system':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_magnetic_field_generator_2',	storages:{ 'magnetic_field_generator':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_nuclear_pasta_2',	storages:{ 'nuclear_pasta':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_thermal_propulsion_rocket_2',	storages:{ 'thermal_propulsion_rocket':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_biochemical_sculptor_2',	storages:{ 'biochemical_sculptor':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_ai_expansion_server_2',	storages:{ 'ai_expansion_server':100 },	assign:{ id:'storage_container_2', count:0 },	},
	{	type:'storer',	id:'storer_ballistic_warp_drive_2',	storages:{ 'ballistic_warp_drive':100 },	assign:{ id:'storage_container_2', count:0 },	},
	
	{	type:'storer',	id:'storer_water_1',	storages:{ 'water':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	{	type:'storer',	id:'storer_crude_oil_1',	storages:{ 'crude_oil':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	{	type:'storer',	id:'storer_nitrogen_gas_1',	storages:{ 'nitrogen_gas':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	{	type:'storer',	id:'storer_fuel_1',	storages:{ 'fuel':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	{	type:'storer',	id:'storer_alumina_solution_1',	storages:{ 'alumina_solution':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	{	type:'storer',	id:'storer_sulfuric_acid_1',	storages:{ 'sulfuric_acid':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	{	type:'storer',	id:'storer_dark_matter_residue_1',	storages:{ 'dark_matter_residue':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	{	type:'storer',	id:'storer_excited_photonic_matter_1',	storages:{ 'excited_photonic_matter':400 },	assign:{ id:'fluid_buffer_1', count:0 },	},
	
	{	type:'storer',	id:'storer_water_2',	storages:{ 'water':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	{	type:'storer',	id:'storer_crude_oil_2',	storages:{ 'crude_oil':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	{	type:'storer',	id:'storer_nitrogen_gas_2',	storages:{ 'nitrogen_gas':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	{	type:'storer',	id:'storer_fuel_2',	storages:{ 'fuel':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	{	type:'storer',	id:'storer_alumina_solution_2',	storages:{ 'alumina_solution':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	{	type:'storer',	id:'storer_sulfuric_acid_2',	storages:{ 'sulfuric_acid':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	{	type:'storer',	id:'storer_dark_matter_residue_2',	storages:{ 'dark_matter_residue':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	{	type:'storer',	id:'storer_excited_photonic_matter_2',	storages:{ 'excited_photonic_matter':800 },	assign:{ id:'fluid_buffer_2', count:0 },	},
	
	// PRODUCERS

	{	type:'producer',	id:'producer_iron_ore_0',	outputs:{ 'iron_ore':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_copper_ore_0',	outputs:{ 'copper_ore':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_limestone_0',	outputs:{ 'limestone':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_biomass_0',	outputs:{ 'biomass':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_coal_0',	outputs:{ 'coal':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_caterium_ore_0',	outputs:{ 'caterium_ore':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_bauxite_0',	outputs:{ 'bauxite':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_raw_quartz_0',	outputs:{ 'raw_quartz':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_sulfur_0',	outputs:{ 'sulfur':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_uranium_0',	outputs:{ 'uranium':0.5 },	assign:{ id:'miner_0', count:0 },	},
	{	type:'producer',	id:'producer_sam_0',	outputs:{ 'sam':0.5 },	assign:{ id:'miner_0', count:0 },	},

	{	type:'producer',	id:'producer_iron_ore_1',	outputs:{ 'iron_ore':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_copper_ore_1',	outputs:{ 'copper_ore':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_limestone_1',	outputs:{ 'limestone':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_biomass_1',	outputs:{ 'biomass':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_coal_1',	outputs:{ 'coal':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_caterium_ore_1',	outputs:{ 'caterium_ore':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_bauxite_1',	outputs:{ 'bauxite':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_raw_quartz_1',	outputs:{ 'raw_quartz':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_sulfur_1',	outputs:{ 'sulfur':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_uranium_1',	outputs:{ 'uranium':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},
	{	type:'producer',	id:'producer_sam_1',	outputs:{ 'sam':1 },	assign:{ id:'miner_1', count:0 },	costs:{ 'energy':5e6 },	},

	{	type:'producer',	id:'producer_iron_ore_2',	outputs:{ 'iron_ore':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_copper_ore_2',	outputs:{ 'copper_ore':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_limestone_2',	outputs:{ 'limestone':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_biomass_2',	outputs:{ 'biomass':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_coal_2',	outputs:{ 'coal':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_caterium_ore_2',	outputs:{ 'caterium_ore':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_bauxite_2',	outputs:{ 'bauxite':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_raw_quartz_2',	outputs:{ 'raw_quartz':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_sulfur_2',	outputs:{ 'sulfur':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_uranium_2',	outputs:{ 'uranium':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},
	{	type:'producer',	id:'producer_sam_2',	outputs:{ 'sam':2 },	assign:{ id:'miner_2', count:0 },	costs:{ 'energy':15e6 },	},

	{	type:'producer',	id:'producer_iron_ore_3',	outputs:{ 'iron_ore':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_copper_ore_3',	outputs:{ 'copper_ore':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_limestone_3',	outputs:{ 'limestone':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_biomass_3',	outputs:{ 'biomass':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_coal_3',	outputs:{ 'coal':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_caterium_ore_3',	outputs:{ 'caterium_ore':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_bauxite_3',	outputs:{ 'bauxite':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_raw_quartz_3',	outputs:{ 'raw_quartz':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_sulfur_3',	outputs:{ 'sulfur':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_uranium_3',	outputs:{ 'uranium':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},
	{	type:'producer',	id:'producer_sam_3',	outputs:{ 'sam':4 },	assign:{ id:'miner_3', count:0 },	costs:{ 'energy':45e6 },	},

	{	type:'producer',	id:'producer_water',	outputs:{ 'water':2 },	assign:{ id:'water_extractor', count:0 },	costs:{ 'energy':20e6 },	},

	{	type:'producer',	id:'producer_crude_oil',	outputs:{ 'crude_oil':1 },	assign:{ id:'oil_extractor', count:0 },	costs:{ 'energy':40e6 },	},

	{	type:'producer',	id:'producer_nitrogen_gas',	outputs:{ 'nitrogen_gas':1 },	assign:{ id:'gas_extractor', count:0 },	costs:{ 'energy':150e6 },	},

	{	type:'producer',	id:'producer_iron_ingot',	outputs:{ 'iron_ingot':0.5 },	assign:{ id:'smelter', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'iron_ore':0.5 },	},
	{	type:'producer',	id:'producer_copper_ingot',	outputs:{ 'copper_ingot':0.5 },	assign:{ id:'smelter', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ore':0.5 },	},
	{	type:'producer',	id:'producer_caterium_ingot',	outputs:{ 'caterium_ingot':0.5 },	assign:{ id:'smelter', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'caterium_ore':0.5 },	},

	{	type:'producer',	id:'producer_aluminum_casing',	outputs:{ 'aluminum_casing':1 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'aluminum_ingot':1.5 },	},
	{	type:'producer',	id:'producer_cable',	outputs:{ 'cable':0.5 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'wire':1 },	},
	{	type:'producer',	id:'producer_concrete',	outputs:{ 'concrete':0.25 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'limestone':0.75 },	},
	{	type:'producer',	id:'producer_copper_powder',	outputs:{ 'copper_powder':0.75 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ingot':5 },	},
	{	type:'producer',	id:'producer_copper_sheet',	outputs:{ 'copper_sheet':0.25 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ingot':0.5 },	},
	{	type:'producer',	id:'producer_ficsite_trigon',	outputs:{ 'ficsite_trigon':0.25 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'ficsite_ingot':0.75 },	},
	{	type:'producer',	id:'producer_iron_plate',	outputs:{ 'iron_plate':0.25 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'iron_ingot':0.5 },	},
	{	type:'producer',	id:'producer_iron_rode',	outputs:{ 'iron_rod':0.25 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'iron_ingot':0.25 },	},
	{	type:'producer',	id:'producer_quickwire',	outputs:{ 'quickwire':0.2 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'caterium_ingot':1 },	},
	{	type:'producer',	id:'producer_reanimated_sam',	outputs:{ 'reanimated_sam':0.5 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'sam':2 },	},
	{	type:'producer',	id:'producer_screw',	outputs:{ 'screw':0.8 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'iron_rod':0.2 },	},
	{	type:'producer',	id:'producer_steel_beam',	outputs:{ 'steel_beam':0.25 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'steel_ingot':1 },	},
	{	type:'producer',	id:'producer_steel_pipe',	outputs:{ 'steel_pipe':0.2 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'steel_ingot':0.3 },	},
	{	type:'producer',	id:'producer_wire',	outputs:{ 'wire':0.5 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'copper_ingot':0.25 },	},
	{	type:'producer',	id:'producer_quartz_crystal',	outputs:{ 'quartz_crystal':22.5/60 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'raw_quartz':37.5/60 },	},
	{	type:'producer',	id:'producer_silica',	outputs:{ 'silica':37.5/60 },	assign:{ id:'builder', count:0 },	costs:{ 'energy':4e6 },	inputs:{ 'raw_quartz':22.5/60 },	},

	{	type:'producer',	id:'producer_ai_limiter',	outputs:{ 'ai_limiter':5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'copper_sheet':25/60, 'quickwire':100/60 },	},
	{	type:'producer',	id:'producer_alclad_aluminum_sheet',	outputs:{ 'alclad_aluminum_sheet':30/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'aluminum_ingot':30/60, 'copper_ingot':10/60 },	},
	{	type:'producer',	id:'producer_assembly_director_system',	outputs:{ 'assembly_director_system':0.75/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'adaptive_control_unit':1.5/60, 'supercomputer':0.75/60 },	},
	{	type:'producer',	id:'producer_automated_wiring',	outputs:{ 'automated_wiring':2.5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'stator':2.5/60, 'cable':50/60 },	},
	{	type:'producer',	id:'producer_circuit_board',	outputs:{ 'circuit_board':7.5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'copper_sheet':15/60, 'plastic':30/60 },	},
	{	type:'producer',	id:'producer_electromagnetic_control_rod',	outputs:{ 'electromagnetic_control_rod':4/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'stator':6/60, 'ai_limiter':4/60 },	},
	{	type:'producer',	id:'producer_encased_industrial_beam',	outputs:{ 'encased_industrial_beam':6/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'steel_beam':18/60, 'concrete':36/60 },	},
	{	type:'producer',	id:'producer_heat_sink',	outputs:{ 'heat_sink':7.5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'alclad_aluminum_sheet':37.5/60, 'copper_sheet':22.5/60 },	},
	{	type:'producer',	id:'producer_magnetic_field_generator',	outputs:{ 'magnetic_field_generator':1/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'versatile_framework':2.5/60, 'electromagnetic_control_rod':1/60 },	},
	{	type:'producer',	id:'producer_modular_frame',	outputs:{ 'modular_frame':2/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'reinforced_iron_plate':3/60, 'iron_rod':12/60 },	},
	{	type:'producer',	id:'producer_motor',	outputs:{ 'motor':5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'rotor':10/60, 'stator':10/60 },	},
	{	type:'producer',	id:'producer_pressure_conversion_cube',	outputs:{ 'pressure_conversion_cube':1/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'fused_modular_frame':1/60, 'radio_control_unit':2/60 },	},
	{	type:'producer',	id:'producer_reinforced_iron_plate',	outputs:{ 'reinforced_iron_plate':5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'iron_plate':30/60, 'screw':60/60 },	},
	{	type:'producer',	id:'producer_rotor',	outputs:{ 'rotor':4/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'iron_rod':20/60, 'screw':100/60 },	},
	{	type:'producer',	id:'producer_smart_plating',	outputs:{ 'smart_plating':2/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'reinforced_iron_plate':2/60, 'rotor':2/60 },	},
	{	type:'producer',	id:'producer_stator',	outputs:{ 'stator':5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'steel_pipe':15/60, 'wire':40/60 },	},
	{	type:'producer',	id:'producer_versatile_framework',	outputs:{ 'versatile_framework':5/60 },	assign:{ id:'assembler', count:0 },	costs:{ 'energy':15e6 },	inputs:{ 'modular_frame':2.5/60, 'steel_beam':30/60 },	},

	{	type:'producer',	id:'producer_aluminum_ingot',	outputs:{ 'aluminum_ingot':60/60 },	assign:{ id:'foundry', count:0 },	costs:{ 'energy':16e6 },	inputs:{ 'aluminum_scrap':90/60, 'silica':5/60 },	},
	{	type:'producer',	id:'producer_steel_ingot',	outputs:{ 'steel_ingot':45/60 },	assign:{ id:'foundry', count:0 },	costs:{ 'energy':16e6 },	inputs:{ 'iron_ore':45/60, 'coal':45/60 },	},

	{	type:'producer',	id:'producer_alumina_solution',	outputs:{ 'alumina_solution':120/60 },	assign:{ id:'refinery', count:0 },	costs:{ 'energy':30e6 },	inputs:{ 'bauxite':120/60, 'water':180/60 },	},
	{	type:'producer',	id:'producer_aluminum_scrap',	outputs:{ 'aluminum_scrap':360/60 },	assign:{ id:'refinery', count:0 },	costs:{ 'energy':30e6 },	inputs:{ 'alumina_solution':240/60, 'coal':120/60 },	},
	{	type:'producer',	id:'producer_fuel',	outputs:{ 'fuel':40/60 },	assign:{ id:'refinery', count:0 },	costs:{ 'energy':30e6 },	inputs:{ 'crude_oil':60/60 },	},
	{	type:'producer',	id:'producer_plastic',	outputs:{ 'plastic':20/60 },	assign:{ id:'refinery', count:0 },	costs:{ 'energy':30e6 },	inputs:{ 'crude_oil':30/60 },	},
	{	type:'producer',	id:'producer_rubber',	outputs:{ 'rubber':20/60 },	assign:{ id:'refinery', count:0 },	costs:{ 'energy':30e6 },	inputs:{ 'crude_oil':30/60 },	},
	{	type:'producer',	id:'producer_sulfuric_acid',	outputs:{ 'sulfuric_acid':50/60 },	assign:{ id:'refinery', count:0 },	costs:{ 'energy':30e6 },	inputs:{ 'sulfur':50/60, 'water':50/60 },	},

	{	type:'producer',	id:'producer_adaptive_control_unit',	outputs:{ 'adaptive_control_unit':1/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'automated_wiring':5/60, 'circuit_board':5/60, 'heavy_modular_frame':1/60, 'computer':2/60 },	},
	{	type:'producer',	id:'producer_ballistic_warp_drive',	outputs:{ 'ballistic_warp_drive':1/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'thermal_propulsion_rocket':1/60, 'singularity_cell':5/60, 'superposition_oscillator':2/60, 'dark_matter_crystal':40/60 },	},
	{	type:'producer',	id:'producer_computer',	outputs:{ 'computer':2.5/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'circuit_board':10/60, 'cable':20/60, 'plastic':40/60 },	},
	{	type:'producer',	id:'producer_crystal_oscillator',	outputs:{ 'crystal_oscillator':1/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'quartz_crystal':18/60, 'cable':14/60, 'reinforced_iron_plate':2.5/60 },	},
	{	type:'producer',	id:'producer_heavy_modular_frame',	outputs:{ 'heavy_modular_frame':2/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'modular_frame':10/60, 'steel_pipe':40/60, 'encased_industrial_beam':10/60, 'screw':240/60 },	},
	{	type:'producer',	id:'producer_high_speed_connector',	outputs:{ 'high_speed_connector':3.75/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'quickwire':210/60, 'cable':37.5/60, 'circuit_board':3.75/60 },	},
	{	type:'producer',	id:'producer_modular_engine',	outputs:{ 'modular_engine':1/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'motor':2/60, 'rubber':15/60, 'smart_plating':2/60 },	},
	{	type:'producer',	id:'producer_radio_control_unit',	outputs:{ 'radio_control_unit':2.5/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'aluminum_casing':40/60, 'crystal_oscillator':1.25/60, 'computer':2.5/60 },	},
	{	type:'producer',	id:'producer_sam_fluctuator',	outputs:{ 'sam_fluctuator':10/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'reanimated_sam':60/60, 'wire':50/60, 'steel_pipe':30/60 },	},
	{	type:'producer',	id:'producer_singularity_cell',	outputs:{ 'singularity_cell':10/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'nuclear_pasta':1/60, 'dark_matter_crystal':20/60, 'iron_plate':100/60, 'concrete':200/60 },	},
	{	type:'producer',	id:'producer_supercomputer',	outputs:{ 'supercomputer':1.875/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'computer':7.5/60, 'ai_limiter':3.75/60, 'high_speed_connector':5.625/60, 'plastic':52.5/60 },	},
	{	type:'producer',	id:'producer_thermal_propulsion_rocket',	outputs:{ 'thermal_propulsion_rocket':1/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'modular_engine':2.5/60, 'turbo_motor':1/60, 'cooling_system':3/60, 'fused_modular_frame':1/60 },	},
	{	type:'producer',	id:'producer_turbo_motor',	outputs:{ 'turbo_motor':1.875/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'cooling_system':7.5/60, 'radio_control_unit':3.75/60, 'motor':7.5/60, 'rubber':45/60 },	},
	{	type:'producer',	id:'producer_uranium_fuel_rod',	outputs:{ 'uranium_fuel_rod':0.4/60 },	assign:{ id:'manufacturer', count:0 },	costs:{ 'energy':55e6 },	inputs:{ 'encased_uranium_cell':20/60, 'encased_industrial_beam':1.2/60, 'electromagnetic_control_rod':2/60 },	},

	{	type:'producer',	id:'producer_battery',	outputs:{ 'battery':20/60 },	assign:{ id:'blender', count:0 },	costs:{ 'energy':75e6 },	inputs:{ 'sulfuric_acid':50/60, 'alumina_solution':40/60, 'aluminum_casing':20/60 },	},
	{	type:'producer',	id:'producer_biochemical_sculptor',	outputs:{ 'biochemical_sculptor':2/60 },	assign:{ id:'blender', count:0 },	costs:{ 'energy':75e6 },	inputs:{ 'assembly_director_system':0.5/60, 'ficsite_trigon':40/60, 'water':10/60 },	},
	{	type:'producer',	id:'producer_cooling_system',	outputs:{ 'cooling_system':6/60 },	assign:{ id:'blender', count:0 },	costs:{ 'energy':75e6 },	inputs:{ 'heat_sink':12/60, 'rubber':12/60, 'water':30/60, 'nitrogen_gas':150/60 },	},
	{	type:'producer',	id:'producer_encased_uranium_cell',	outputs:{ 'encased_uranium_cell':25/60 },	assign:{ id:'blender', count:0 },	costs:{ 'energy':75e6 },	inputs:{ 'uranium':50/60, 'concrete':15/60, 'sulfuric_acid':40/60 },	},
	{	type:'producer',	id:'producer_fused_modular_frame',	outputs:{ 'fused_modular_frame':1.5/60 },	assign:{ id:'blender', count:0 },	costs:{ 'energy':75e6 },	inputs:{ 'heavy_modular_frame':1.5/60, 'aluminum_casing':75/60, 'nitrogen_gas':37.5/60 },	},
	{	type:'producer',	id:'producer_nitric_acid',	outputs:{ 'nitric_acid':30/60 },	assign:{ id:'blender', count:0 },	costs:{ 'energy':75e6 },	inputs:{ 'nitrogen_gas':120/60, 'water':30/60, 'iron_plate':10/60 },	},

	{	type:'producer',	id:'producer_dark_matter_crystal',	outputs:{ 'dark_matter_crystal':30/60 },	assign:{ id:'particle_accelerator', count:0 },	costs:{ 'energy':1000e6 },	inputs:{ 'diamonds':30/60, 'dark_matter_residue':150/60 },	},
	{	type:'producer',	id:'producer_diamonds',	outputs:{ 'diamonds':30/60 },	assign:{ id:'particle_accelerator', count:0 },	costs:{ 'energy':1000e6 },	inputs:{ 'coal':600/60 },	},
	{	type:'producer',	id:'producer_nuclear_pasta',	outputs:{ 'nuclear_pasta':0.5/60 },	assign:{ id:'particle_accelerator', count:0 },	costs:{ 'energy':1000e6 },	inputs:{ 'copper_powder':100/60, 'pressure_conversion_cube':0.5/60 },	},

	{	type:'producer',	id:'producer_ficsite_ingot_1',	outputs:{ 'ficsite_ingot':30/60 },	assign:{ id:'converter', count:0 },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':60/60, 'aluminum_ingot':120/60 },	},
	{	type:'producer',	id:'producer_ficsite_ingot_2',	outputs:{ 'ficsite_ingot':15/60 },	assign:{ id:'converter', count:0 },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':45/60, 'caterium_ingot':60/60 },	},
	{	type:'producer',	id:'producer_ficsite_ingot_3',	outputs:{ 'ficsite_ingot':10/60 },	assign:{ id:'converter', count:0 },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':40/60, 'iron_ingot':240/60 },	},
	{	type:'producer',	id:'producer_time_crystal',	outputs:{ 'time_crystal':6/60 },	assign:{ id:'converter', count:0 },	costs:{ 'energy':250e6 },	inputs:{ 'diamonds':12/60 },	},
	{	type:'producer',	id:'producer_dark_matter_residue',	outputs:{ 'dark_matter_residue':100/60 },	assign:{ id:'converter', count:0 },	costs:{ 'energy':250e6 },	inputs:{ 'reanimated_sam':50/60 },	},
	{	type:'producer',	id:'producer_excited_photonic_matter',	outputs:{ 'excited_photonic_matter':200/60 },	assign:{ id:'converter', count:0 },	costs:{ 'energy':250e6 },	},

	{	type:'producer',	id:'producer_ai_expansion_server',	outputs:{ 'ai_expansion_server':4/60 },	assign:{ id:'quantum_encoder', count:0 },	costs:{ 'energy':1000e6 },	inputs:{ 'magnetic_field_generator':4/60, 'neural_quantum_processor':4/60, 'superposition_oscillator':4/60, 'excited_photonic_matter':100/60 },	},
	{	type:'producer',	id:'producer_neural_quantum_processor',	outputs:{ 'neural_quantum_processor':3/60 },	assign:{ id:'quantum_encoder', count:0 },	costs:{ 'energy':1000e6 },	inputs:{ 'time_crystal':15/60, 'supercomputer':3/60, 'ficsite_trigon':45/60, 'excited_photonic_matter':75/60 },	},
	{	type:'producer',	id:'producer_superposition_oscillator',	outputs:{ 'superposition_oscillator':5/60 },	assign:{ id:'quantum_encoder', count:0 },	costs:{ 'energy':1000e6 },	inputs:{ 'dark_matter_crystal':30/60, 'crystal_oscillator':5/60, 'alclad_aluminum_sheet':45/60, 'excited_photonic_matter':125/60 },	},
]